----------------------------------------------------------------------
-- GENERATED BY GameDBPreBuild.lua, DO NOT MODIFY
----------------------------------------------------------------------

Data = 
{
	DBName = "RumpusData",
	ID = 10,
	PackageName = "Spiderman",
	Records = 
	{
		
		{
			AudioBank = "",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "SPD_Skycycle_PS",
			Id = 6495,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "SPD_HawkeyeSkycycle",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Spiderman",
			PreviewFile = "Icon/ICON_TB_Hawkeye_SkyCycle",
			PreviewType = "Terrain",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "SPD_SHLD_Hovercar_PS",
			Id = 6493,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "SPD_SHLD_Hovercar",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Spiderman",
			PreviewFile = "Icon/ICON_SPD_SHLD_Hovercar_Car",
			PreviewType = "Terrain",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "",
			CustomizationCategory = "",
			DefaultMaterial = "",
			Filename = "",
			Id = 6718,
			Modifier = "NA",
			["Object Name"] = "SpiderManDummyObj",
			ObjectCategory = "NA",
			ObjectType = "NA",
			PackageName = "Spiderman",
			PreviewFile = "",
			PreviewType = "",
			SelectionOffset = "",
			ShowInMeridian = "NA",
			SwapCreationKey = "",
		},
	},
	Type = "RumpusObjects",
	Version = 0.3,
}


