----------------------------------------------------------------------
-- GENERATED BY GameDBPreBuild.lua, DO NOT MODIFY
----------------------------------------------------------------------

Data = 
{
	DBName = "RumpusData",
	ID = 7,
	PackageName = "Avengers",
	Records = 
	{
		
		{
			AudioBank = "",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "AVG_hawkeye_skycycle_PS",
			Id = 7736,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "AVG_HawkeySkycycle_PS",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Avengers",
			PreviewFile = "",
			PreviewType = "",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "AVG_shld_motorcycle_PS",
			Id = 7737,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "AVG_SHLD_Motorcycle_PS",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Avengers",
			PreviewFile = "Icon/ICON_AVG_SHLD_Motorcycle",
			PreviewType = "Terrain",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "Weapons",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "AVG_Skycycle_PS",
			Id = 7738,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "AVG_Skycycle_PS",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Avengers",
			PreviewFile = "Icon/ICON_AVG_Skycycle_Car",
			PreviewType = "Terrain",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "Weapons",
			CustomizationCategory = "None",
			DefaultMaterial = "",
			Filename = "AVG_Snowmobile_PS",
			Id = 7739,
			Modifier = "M_Normal|M_StatTracker|M_ActorSource",
			["Object Name"] = "AVG_Snowmobile_PS",
			ObjectCategory = "Vehicle",
			ObjectType = "Vehicle",
			PackageName = "Avengers",
			PreviewFile = "Icon/ICON_AVG_Snowmobile",
			PreviewType = "Terrain",
			SelectionOffset = "",
			ShowInMeridian = "NO",
			SwapCreationKey = "",
		},
		
		{
			AudioBank = "",
			CustomizationCategory = "",
			DefaultMaterial = "",
			Filename = "",
			Id = 6720,
			Modifier = "NA",
			["Object Name"] = "AvengersDummyObj",
			ObjectCategory = "NA",
			ObjectType = "NA",
			PackageName = "Avengers",
			PreviewFile = "",
			PreviewType = "",
			SelectionOffset = "",
			ShowInMeridian = "NA",
			SwapCreationKey = "",
		},
	},
	Type = "RumpusObjects",
	Version = 0.3,
}


