----------------------------------------------------------------------
-- GENERATED BY GameDBPreBuild.lua, DO NOT MODIFY
----------------------------------------------------------------------

Data = 
{
	DBName = "Inventory",
	ID = 8,
	PackageName = "Spiderman",
	Records = 
	{
		
		{
			AllowExt = true,
			AllowInt = false,
			Categories = 
			{
				20,
				0,
				0,
				0,
				13,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
			},
			UID = 3643,
			count = 1,
			enabled = 1,
			inUseCount = 0,
			levelUp = 0,
			maxCount = 2,
			maxOwned = 1,
			name = "INV_SPD_HawkeyeSkycycle",
			playSetFilter = "LVL_SPIDERMAN",
			rroName = "SPD_HawkeyeSkycycle",
			sortOrder = 2195,
			state = 1,
			stateData = "P\xbd\xa2v\xe1\n6\x93\xd08\x8a\x1e$\xc6\x11\x90",
			status = "Unassigned",
			type = "CAT_VEHICLE_FLYING",
			usageCost = 5,
		},
		
		{
			AllowExt = true,
			AllowInt = false,
			Categories = 
			{
				20,
				0,
				0,
				0,
				13,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
			},
			UID = 3638,
			count = 1,
			enabled = 1,
			inUseCount = 0,
			levelUp = 0,
			maxCount = 2,
			maxOwned = 1,
			name = "INV_SPD_SHLD_Hovercar",
			playSetFilter = "LVL_SPIDERMAN",
			rroName = "SPD_SHLD_Hovercar",
			sortOrder = 2194,
			state = 1,
			stateData = "d\xf2\xc2\xe4\x90\x85\xeda\xe7\xd1l\xd4\xa7_\xd1\b",
			status = "Unassigned",
			type = "CAT_VEHICLE_FLYING",
			usageCost = 5,
		},
	},
	TableName = "inventoryItems",
	Type = "Inventory",
	Version = 0.1,
}


