--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--


--Version = 0.3

Data =
{
	DBName = "Locks",
	Type = "Locks",
	Version = 0.3,
	ID = 157,
	TableName = "locks",
	Records =
	{
		{
			UID = 87872,
			name = 'CC_SM_HULK',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\a`\x00\xa8k*\xbe\x8d\x95+e\xf906\x8f4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_Hulk",
				},
			},
		},
		{
			UID = 87875,
			name = 'CC_SM_IRONMAN',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\x13g\x82RR\xb0\xcf\x85(_em;;j_",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_IronMan",
				},
			},
		},
		{
			UID = 88674,
			name = 'INV_NPC_RR_GreenGoblin',
			iconname = 'RR_GreenGoblin_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "Ck`l0\x1a\x95w\xb7\x89\xc1\xf0\x0f\xc8\x7fj",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_GreenGoblin",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_GreenGoblin",
				},
			},
		},
		{
			UID = 88553,
			name = 'INV_NPC_RR_IronFist',
			iconname = 'RR_IronFist_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "-\xd4\xb92=]\x14\xb4\xaaV\xec\xa4\x1e6\xdeq",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_IronFist",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_IronFist",
				},
			},
		},
		{
			UID = 88622,
			name = 'INV_NPC_RR_NickFury',
			iconname = 'RR_NickFury_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "M\xbf1@\xce\x92\xb6\x91\xedl'\xd0\x88\xedh\xec",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_NickFury",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_NickFury",
				},
			},
		},
		{
			UID = 88615,
			name = 'INV_NPC_RR_Nova',
			iconname = 'RR_Nova_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xddBW\x93\x95\xa2{\xfepEY\x18OB\x05,",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Nova",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Nova",
				},
			},
		},
		{
			UID = 88624,
			name = 'INV_NPC_RR_SpiderMan',
			iconname = 'RR_SpiderMan_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xbe\x16\xceJ\xadt\x00\x8e\xe6\x87\x91\xf1;\x9b\xa1\xc9",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_SpiderMan",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Spiderman",
				},
			},
		},
		{
			UID = 88669,
			name = 'INV_NPC_RR_Venom',
			iconname = 'RR_Venom_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "m}\xa4a\x8a\xc6\x9ci\xf3\xa1D\xba\x84S;e",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Venom",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Venom",
				},
			},
		},
		{
			UID = 85510,
			name = 'INV_TB_HawkeyeSkycycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\xe57Y-[\xba\x9c\xa0\xc94y\xfbs\x19\xd9\xde",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_HawkeyeSkycycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
		{
			UID = 113163,
			name = 'INV_TB_SHLD_Hovercar',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "x\x12J{W\xa2j*B\xfb\x10\x00)\xf6\x9b\xa1",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_SHLD_Hovercar",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
	},
}
