----------------------------------------------------------------------
-- GENERATED BY GameDBPreBuild.lua, DO NOT MODIFY
----------------------------------------------------------------------

Data = 
{
	Categories = 
	{
		"MCAT_Classic",
		"MCAT_Terrain",
		"MCAT_Buildings",
		"MCAT_Decorations",
		"MCAT_VehiclesActors",
		"MCAT_SimpleToys",
		"MCAT_GameMakers",
		"MCAT_ToyOrigin",
		"MCAT_Template",
		"MCINT_Standard",
		"MCINT_HomeEssentials",
		"MCINT_FamousFurniture",
		"MCINT_NPCActors",
	},
	Items = 
	{
		
		{
			List = 
			{
				"SUB_None",
				"CAT_BUILDING",
				"CAT_SETPIECE",
				"CAT_BUILDSET_01",
				"CAT_BUILDSET_02",
				"CAT_BUILDSET_03",
				"CAT_BUILDSET_04",
				"CAT_BUILDSET_05",
				"CAT_BUILDSET_06",
				"CAT_BUILDSET_07",
				"CAT_TRACK_PIECE",
				"CAT_IN2_TEMPLATES",
				"CAT_IN2_BRUSHES",
				"CAT_LOGICTOYS",
				"CAT_DECORATION",
				"CAT_BASICBLOCKS",
				"CAT_FOLIAGE",
				"CAT_TERRAIN",
				"CAT_INSTANTFUN",
				"CAT_VEHICLE_GROUND",
				"CAT_VEHICLE_FLYING",
				"CAT_MOUNT",
				"CAT_GAMEPLAY",
				"CAT_PLATFORMING",
				"CAT_SPORTSTOYS",
				"CAT_ENEMY",
				"CAT_SIDEKICKS",
				"CAT_CRITTER",
				"CAT_NPC_CASTMEMBERS",
				"CAT_NPC_AVATARS",
				"CAT_NPC_TBX",
				"CAT_NPC_PLAYSET_IN1",
				"CAT_NPC_PLAYSET_IN2",
				"CAT_NPC_PLAYSET_IN3",
			},
			Name = "MCAT_Classic",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_FlatTerrain",
				"SUB_SlopesRamps",
				"SUB_RockyTerrain",
				"SUB_CliffsLedges",
				"SUB_CavernTunnel",
				"SUB_Water",
			},
			Name = "MCAT_Terrain",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_BldSet_StarWars",
				"SUB_BldSet_Tatooine",
				"SUB_BldSet_DeathStar",
				"SUB_BldSet_Ewok",
				"SUB_BldSet_InsideOut",
				"SUB_BldSet_NBC",
				"SUB_BldSet_Frozen",
				"SUB_BldSet_TML",
				"SUB_BldSet_GFA",
				"SUB_BldSet_SR",
				"SUB_MainStreetUSA",
				"SUB_TreeHouse",
				"SUB_Cottage",
				"SUB_BldSet_Farm",
				"SUB_BldSet_Brave",
				"SUB_Castle",
				"SUB_Agrabah",
				"SUB_BldSet_BH6",
				"SUB_MarvelCity",
				"SUB_MarvelSuburbs",
				"SUB_Asgardian",
				"SUB_SpaceStation",
				"SUB_Disney",
				"SUB_Basic",
				"SUB_ClassicIN1",
				"SUB_FamousLocations",
				"SUB_Brushes",
			},
			Name = "MCAT_Buildings",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_Bushes",
				"SUB_City",
				"SUB_Clusters",
				"SUB_Country",
				"SUB_Exotic",
				"SUB_Flowers",
				"SUB_Home",
				"SUB_Misc",
				"SUB_SignsHighway",
				"SUB_Statues",
				"SUB_Trees",
				"SUB_Yard",
			},
			Name = "MCAT_Decorations",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_Avatars",
				"SUB_Brushes",
				"SUB_CastMembers",
				"SUB_Critters",
				"SUB_Enemies",
				"SUB_Marvel",
				"SUB_Mounts",
				"SUB_NonPlayset",
				"SUB_Playset",
				"SUB_Sidekicks",
				"SUB_StarWars",
				"SUB_Vehicles_Ground",
				"SUB_Vehicles_Flying",
			},
			Name = "MCAT_VehiclesActors",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_ActiveBlocks",
				"SUB_BasicBlocks",
				"SUB_BasicToys",
				"SUB_Movers",
				"SUB_Physics",
			},
			Name = "MCAT_SimpleToys",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_Collectibles",
				"SUB_DisneyGames",
				"SUB_DrivingToys",
				"SUB_GameRules",
				"SUB_GameTemplates",
				"SUB_LogicToys",
				"SUB_MarvelGames",
				"SUB_Other",
				"SUB_PlatformingToys",
				"SUB_Rails",
				"SUB_SportsToys",
				"SUB_StarWarsGames",
			},
			Name = "MCAT_GameMakers",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_Asgard",
				"SUB_Avengers",
				"SUB_Brave",
				"SUB_Cars",
				"SUB_CloneWars",
				"SUB_Empire",
				"SUB_Guardians",
				"SUB_Incredibles",
				"SUB_InsideOut",
				"SUB_Kyln",
				"SUB_LoneRanger",
				"SUB_MonstersU",
				"SUB_Pirates",
				"SUB_PSX",
				"SUB_Speedway",
				"SUB_SpiderMan",
				"SUB_Stitch",
				"SUB_Takeover",
				"SUB_ToyStory",
				"SUB_MBA",
				"SUB_Dory",
			},
			Name = "MCAT_ToyOrigin",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_ReadyToPlay",
				"SUB_GameKits",
				"SUB_GameComponents",
				"SUB_WorldComponents",
			},
			Name = "MCAT_Template",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_AccentDecor",
				"SUB_NPC_CastMembers",
				"SUB_CeilingDecoration",
				"SUB_LogicToy",
				"SUB_NPC_Critter",
				"SUB_ElectronAppli",
				"SUB_FloorDecoration",
				"SUB_NPC_Interior",
				"SUB_Rooms",
				"SUB_Rugs",
				"SUB_SeatBed",
				"SUB_Sidekicks",
				"SUB_TablesCabinets",
				"SUB_WallDecoration",
				"SUB_WallHangings",
				"SUB_Windows",
			},
			Name = "MCINT_Standard",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_SeatBed",
				"SUB_ElectronAppli",
				"SUB_TablesCabinets",
				"SUB_AccentDecor",
				"SUB_Rugs",
				"SUB_WallHangings",
				"SUB_Windows",
			},
			Name = "MCINT_HomeEssentials",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_DisneyFamToys",
				"SUB_MarvelFamToys",
			},
			Name = "MCINT_FamousFurniture",
		},
		
		{
			List = 
			{
				"SUB_None",
				"SUB_Avatars",
				"SUB_CastMembers",
				"SUB_Critters",
				"SUB_Marvel",
				"SUB_NonPlayset",
				"SUB_Playset",
			},
			Name = "MCINT_NPCActors",
		},
	},
}


