--*************************************************
--
-- THIS IS A GENERATED FILE. DO NOT HAND EDIT IT.
-- Generated by Game/Content/Bitmasks/Scripts/TypeDataHelpers.lua
--
--*************************************************

Data =
{
	Version = 0.0,
	Package = 'CivilWar',
	Sets =
	{
		-- Engine Masks/Filters
		{
			set = 'ActorType',
			properties =
			{
				DefaultBitmaskSize = 6,
				Type = 'Properties',
			},
			count = 43,
			masks =
			{
				{	mask='AV_Drax', 	UID=4396 },
				{	mask='AV_Falcon', 	UID=5258 },
				{	mask='AV_Gamora', 	UID=4503 },
				{	mask='AV_GreenGoblin', 	UID=5059 },
				{	mask='AV_Groot', 	UID=4369 },
				{	mask='AV_IronFist', 	UID=4393 },
				{	mask='AV_Loki', 	UID=4352 },
				{	mask='AV_Loki_Decoy', 	UID=5441 },
				{	mask='AV_NickFury', 	UID=4341 },
				{	mask='AV_NickFury_Decoy', 	UID=5073 },
				{	mask='AV_Nova', 	UID=4392 },
				{	mask='AV_RocketRaccoon', 	UID=4370 },
				{	mask='AV_Ronan', 	UID=4389 },
				{	mask='AV_Spiderman', 	UID=4344 },
				{	mask='AV_StarLord', 	UID=4386 },
				{	mask='AV_Venom', 	UID=4377 },
				{	mask='AV_Yondu', 	UID=5228 },
			},
			filters = 
			{
				{	filter='AV_AvatarAvengers', 	desc='AV_Falcon|AV_Loki', 	UID=4374 },
				{	filter='AV_AvatarDecoy', 	desc='AV_NickFury_Decoy|AV_Loki_Decoy', 	UID=5494 },
				{	filter='AV_AvatarGuardians', 	desc='AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu', 	UID=4368 },
				{	filter='AV_AvatarSpiderman', 	desc='AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=4373 },
				{	filter='AV_BruteClass', 	desc='AV_Venom|AV_GreenGoblin', 	UID=5270 },
				{	filter='AV_Fliers', 	desc='AV_Falcon|AV_Nova', 	UID=5668 },
				{	filter='AV_HeroClass', 	desc='AV_Drax|AV_Falcon', 	UID=5359 },
				{	filter='AV_HeroFemaleClass', 	desc='AV_Gamora', 	UID=5357 },
				{	filter='AV_HeroSmallClass', 	desc='AV_Spiderman|AV_Loki|AV_Groot|AV_StarLord|AV_IronFist|AV_NickFury|AV_Nova', 	UID=5360 },
				{	filter='AV_LightsaberBruteClass', 	desc='AV_Venom|AV_GreenGoblin', 	UID=6041 },
				{	filter='AV_LightsaberGirlClass', 	desc='AV_Gamora', 	UID=7356 },
				{	filter='AV_LightsaberHeroClass', 	desc='AV_Falcon|AV_Drax|AV_Ronan', 	UID=7026 },
				{	filter='AV_LightsaberHeroSmallClass', 	desc='AV_Spiderman|AV_Loki|AV_Groot|AV_StarLord|AV_IronFist|AV_NickFury|AV_Nova|AV_Yondu', 	UID=6964 },
				{	filter='AV_RaccoonClass', 	desc='AV_RocketRaccoon', 	UID=5690 },
				{	filter='AV_SuperJumpers', 	desc='AV_Drax|AV_Gamora|AV_IronFist|AV_RocketRaccoon|AV_Spiderman|AV_StarLord|AV_Venom', 	UID=5667 },
				{	filter='AV_SuperStrong', 	desc='AV_Falcon|AV_Loki|AV_Drax|AV_Gamora|AV_Ronan|AV_StarLord|AV_Yondu|AV_IronFist|AV_NickFury|AV_Nova|AV_Spiderman', 	UID=5873 },
				{	filter='AV_TechType', 	desc='AV_RocketRaccoon|AV_StarLord|AV_Yondu|AV_NickFury', 	UID=5872 },
				{	filter='AV_WallCrawlDamagers', 	desc='AV_Groot|AV_Venom', 	UID=5565 },
				{	filter='AV_WallCrawlers', 	desc='AV_Groot|AV_Drax|AV_Spiderman|AV_Venom', 	UID=5564 },
				{	filter='AV_WebSwingers', 	desc='AV_Spiderman|AV_Venom', 	UID=5669 },
			},
			metafilters = 
			{
				{	filter='AV_AvatarAny', 	desc='AV_Falcon|AV_Loki|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=24 },
				{	filter='AV_AvatarBiped', 	desc='AV_Falcon|AV_Loki|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=144 },
				{	filter='AV_IN2_AvatarAny', 	desc='AV_Falcon|AV_Loki|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=5235 },
				{	filter='AboutToBeAttackedList', 	desc='AV_Falcon|AV_Loki|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=2815 },
				{	filter='PlayerControllable', 	desc='AV_Falcon|AV_Loki|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=274 },
				{	filter='RR_zAny', 	desc='AV_Falcon|AV_Loki|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=2137 },
			},
		},
	}
}
