----------------------------------------------------------------------
-- GENERATED BY GameDBPreBuild.lua, DO NOT MODIFY
----------------------------------------------------------------------

Data = 
{
	DBName = "Inventory",
	ID = 8,
	PackageName = "Spiderman",
	Records = 
	{
		
		{
			AllowExt = true,
			AllowInt = false,
			Categories = 
			{
				16916,
				0,
				0,
				0,
				16909,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
			},
			UID = 3643,
			count = 1,
			enabled = 1,
			inUseCount = 0,
			levelUp = 0,
			maxCount = 2,
			maxOwned = 1,
			name = "INV_SPD_HawkeyeSkycycle",
			playSetFilter = "LVL_SPIDERMAN",
			rroName = "SPD_HawkeyeSkycycle",
			sortOrder = 2317,
			state = 1,
			stateData = "\xd19\xe6U4\xdd\xd8\xbd=\xb3$6wfI\xcf",
			status = "Unassigned",
			type = "CAT_VEHICLE_FLYING",
			usageCost = 5,
		},
		
		{
			AllowExt = true,
			AllowInt = false,
			Categories = 
			{
				16404,
				0,
				0,
				0,
				16397,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
			},
			UID = 3638,
			count = 1,
			enabled = 1,
			inUseCount = 0,
			levelUp = 0,
			maxCount = 2,
			maxOwned = 1,
			name = "INV_SPD_SHLD_Hovercar",
			playSetFilter = "LVL_SPIDERMAN",
			rroName = "SPD_SHLD_Hovercar",
			sortOrder = 2316,
			state = 1,
			stateData = "\xb2\x84\x91\xf2RL\fE\xf74X!%e\xa5u",
			status = "Unassigned",
			type = "CAT_VEHICLE_FLYING",
			usageCost = 5,
		},
	},
	TableName = "inventoryItems",
	Type = "Inventory",
	Version = 0.1,
}


