--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--

--Version = 0.3

Data = 
{ 
	Type = "Customization",
	Databases =
	{
		{
			DBName = "BlockheadSidekick",
			Type = "Customization",
			Version = 0.3,

			ID = 6,

			Records =
			{
				Pieces = 
				{
				},
				Materials = 
				{
				},
				Categories = 
				{
					{
						UID = 80725,
						name = 'BHSK',
						iconName = '',
						parentID = 0,
						isLeaf = 0,
						isCharacter = 1,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 80793,
						name = 'ACSK',
						iconName = 'BHSK_ACSK',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 0,
					},
					{
						UID = 80913,
						name = 'Common',
						iconName = '',
						parentID = 80793,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 80919,
						name = 'BSK',
						iconName = 'BHSK_BSK',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 0,
					},
					{
						UID = 80606,
						name = 'Common',
						iconName = '',
						parentID = 80919,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 80948,
						name = 'HDSK',
						iconName = 'BHSK_HDSK',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 1,
					},
					{
						UID = 80607,
						name = 'Common',
						iconName = '',
						parentID = 80948,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 80853,
						name = 'HRSK',
						iconName = 'BHSK_HRSK',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 0,
					},
					{
						UID = 80604,
						name = 'Common',
						iconName = '',
						parentID = 80853,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 99696,
						name = 'HTSK',
						iconName = 'BHSK_HTSK',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 0,
					},
					{
						UID = 99697,
						name = 'Common',
						iconName = '',
						parentID = 99696,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 83522,
						name = 'Mode',
						iconName = '',
						parentID = 80725,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 83538,
						name = 'Brave',
						iconName = '',
						parentID = 83522,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 83576,
						name = 'Kyln',
						iconName = '',
						parentID = 83522,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
				},
				Locators = 
				{
					{
						UID = 80837,
						name = 'Body',
						supportsCustomSize = 0,
						isDestructible = 0,
						minSearchCount = 0,
						allowCache = 0,
					},
					{
						UID = 99695,
						name = 'Hat',
						supportsCustomSize = 0,
						isDestructible = 0,
						minSearchCount = 0,
						allowCache = 0,
					},
					{
						UID = 80690,
						name = 'Head',
						supportsCustomSize = 0,
						isDestructible = 0,
						minSearchCount = 0,
						allowCache = 0,
					},
					{
						UID = 80901,
						name = 'PropLeft_Loc',
						supportsCustomSize = 0,
						isDestructible = 0,
						minSearchCount = 0,
						allowCache = 0,
					},
					{
						UID = 80679,
						name = 'PropRight_Loc',
						supportsCustomSize = 0,
						isDestructible = 0,
						minSearchCount = 0,
						allowCache = 0,
					},
				},
				Colors = 
				{
				},
				Items = 
				{
				},
				Prebuilt = 
				{
					{
						UID = 80768,
						name = 'BlockheadSidekick_CUSTOM',
						lockID = -1,
						initprefix = 'sex=m; master_bone_name = Characters/_Townspeople/_Townspeople.tup;',
						groups =
						{
							{ 80793, -2, -1},
							{ 80919, -2, -1},
							{ 80853, -2, -1},
							{ 80948, -2, -1},
						},
					},
					{
						UID = 80959,
						name = 'BlockheadSidekick_EMPTY',
						lockID = -1,
						initprefix = 'sex=m; master_bone_name = Characters/_Townspeople/_Townspeople.tup;',
						groups =
						{
							{ 80793, -2, -1},
							{ 80919, -2, -1},
							{ 80853, -2, -1},
							{ 80948, -2, -1},
						},
					},
				},
				Excludes = 
				{
				},
				ExcludeOverrides = 
				{
				},
			},
		},
	}, 
} 
