--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--

--Version = 0.3

Data = 
{ 
	Type = "Customization",
	Databases =
	{
		{
			DBName = "DORHand",
			Type = "Customization",
			Version = 0.3,

			ID = 8,

			Records =
			{
				Pieces = 
				{
				},
				Materials = 
				{
				},
				Categories = 
				{
					{
						UID = 118598,
						name = 'DORH',
						iconName = '',
						parentID = 0,
						isLeaf = 0,
						isCharacter = 1,
						isGroup = 0,
						isRequired = 0,
					},
					{
						UID = 118586,
						name = 'Hand',
						iconName = 'DORH_Hand',
						parentID = 118598,
						isLeaf = 0,
						isCharacter = 0,
						isGroup = 1,
						isRequired = 1,
					},
					{
						UID = 118606,
						name = 'Common',
						iconName = '',
						parentID = 118586,
						isLeaf = 1,
						isCharacter = 0,
						isGroup = 0,
						isRequired = 0,
					},
				},
				Locators = 
				{
				},
				Colors = 
				{
					{
						id = 9014,
						setUID = 597,
						colorIndex = 0,
						r = 255,
						g = 255,
						b = 255,
					},
					{
						id = 9012,
						setUID = 597,
						colorIndex = 1,
						r = 228,
						g = 53,
						b = 5,
					},
					{
						id = 38917,
						setUID = 597,
						colorIndex = 2,
						r = 227,
						g = 124,
						b = 2,
					},
					{
						id = 9015,
						setUID = 597,
						colorIndex = 3,
						r = 223,
						g = 209,
						b = 4,
					},
					{
						id = 38755,
						setUID = 597,
						colorIndex = 4,
						r = 136,
						g = 199,
						b = 0,
					},
					{
						id = 9010,
						setUID = 597,
						colorIndex = 5,
						r = 0,
						g = 191,
						b = 92,
					},
					{
						id = 38948,
						setUID = 597,
						colorIndex = 6,
						r = 0,
						g = 200,
						b = 219,
					},
					{
						id = 9017,
						setUID = 597,
						colorIndex = 7,
						r = 35,
						g = 78,
						b = 222,
					},
					{
						id = 38902,
						setUID = 597,
						colorIndex = 8,
						r = 163,
						g = 40,
						b = 219,
					},
					{
						id = 38803,
						setUID = 597,
						colorIndex = 9,
						r = 231,
						g = 55,
						b = 214,
					},
					{
						id = 39024,
						setUID = 597,
						colorIndex = 10,
						r = 227,
						g = 54,
						b = 107,
					},
					{
						id = 38806,
						setUID = 597,
						colorIndex = 11,
						r = 100,
						g = 100,
						b = 100,
					},
					{
						id = 46467,
						setUID = 597,
						colorIndex = 12,
						r = 20,
						g = 20,
						b = 20,
					},
				},
				Items = 
				{
				},
				Prebuilt = 
				{
				},
				Excludes = 
				{
				},
				ExcludeOverrides = 
				{
				},
			},
		},
	}, 
} 
