-----------------------------------------
--  sidekick equiptable items database
--

SideKickItems = 
{
	{
		id =			1,
		name =			"SK_Brave_Green_Healing_AC",
		CustID =		"SK_Brave_Green_Healing_AC",
		lock =			"CUST_SK_Brave_Green_Healing_AC",
		icon =			"SK_Brave_Green_Healing_AC",
	},
	{
		id =			2,
		name =			"SK_Brave_Blue_Healing_AC",
		CustID =		"SK_Brave_Blue_Healing_AC",
		lock =			"CUST_SK_Brave_Blue_Healing_AC",
		icon =			"SK_Brave_Blue_Healing_AC",
	},
	{
		id =			3,
		name =			"SK_Brave_Purple_Healing_AC",
		CustID =		"SK_Brave_Purple_Healing_AC",
		lock =			"CUST_SK_Brave_Purple_Healing_AC",
		icon =			"SK_Brave_Purple_Healing_AC",
	},
	{
		id =			4,
		name =			"SK_Brave_Green_MagicWand_AC",
		CustID =		"SK_Brave_Green_MagicWand_AC",
		lock =			"CUST_SK_Brave_Green_MagicWand_AC",
		icon =			"SK_Brave_Green_MagicWand_AC",
	},
	{
		id =			5,
		name =			"SK_Brave_Blue_MagicWand_AC",
		CustID =		"SK_Brave_Blue_MagicWand_AC",
		lock =			"CUST_SK_Brave_Blue_MagicWand_AC",
		icon =			"SK_Brave_Blue_MagicWand_AC",
	},
	{
		id =			6,
		name =			"SK_Brave_Orange_MagicWand_AC",
		CustID =		"SK_Brave_Orange_MagicWand_AC",
		lock =			"CUST_SK_Brave_Orange_MagicWand_AC",
		icon =			"SK_Brave_Orange_MagicWand_AC",
	},
	{
		id =			7,
		name =			"SK_Brave_Green_Harpoon_AC",
		CustID =		"SK_Brave_Green_Harpoon_AC",
		lock =			"CUST_SK_Brave_Green_Harpoon_AC",
		icon =			"SK_Brave_Green_Harpoon_AC",
	},
	{
		id =			8,
		name =			"SK_Brave_Blue_Harpoon_AC",
		CustID =		"SK_Brave_Blue_Harpoon_AC",
		lock =			"CUST_SK_Brave_Blue_Harpoon_AC",
		icon =			"SK_Brave_Blue_Harpoon_AC",
	},
	{
		id =			9,
		name =			"SK_Brave_Purple_Harpoon_AC",
		CustID =		"SK_Brave_Purple_Harpoon_AC",
		lock =			"CUST_SK_Brave_Purple_Harpoon_AC",
		icon =			"SK_Brave_Purple_Harpoon_AC",
	},
	{
		id =			10,
		name =			"SK_Brave_Green_MagicStaff_AC",
		CustID =		"SK_Brave_Green_MagicStaff_AC",
		lock =			"CUST_SK_Brave_Green_MagicStaff_AC",
		icon =			"SK_Brave_Green_MagicStaff_AC",
	},
	{
		id =			11,
		name =			"SK_Brave_Blue_MagicStaff_AC",
		CustID =		"SK_Brave_Blue_MagicStaff_AC",
		lock =			"CUST_SK_Brave_Blue_MagicStaff_AC",
		icon =			"SK_Brave_Blue_MagicStaff_AC",
	},
	{
		id =			12,
		name =			"SK_Brave_Purple_MagicStaff_AC",
		CustID =		"SK_Brave_Purple_MagicStaff_AC",
		lock =			"CUST_SK_Brave_Purple_MagicStaff_AC",
		icon =			"SK_Brave_Purple_MagicStaff_AC",
	},
	{
		id =			13,
		name =			"SK_Brave_Green_ThowingDagger_AC",
		CustID =		"SK_Brave_Green_ThowingDagger_AC",
		lock =			"CUST_SK_Brave_Green_ThowingDagger_AC",
		icon =			"SK_Brave_Green_ThowingDagger_AC",
	},
	{
		id =			14,
		name =			"SK_Brave_Blue_ThowingDagger_AC",
		CustID =		"SK_Brave_Blue_ThowingDagger_AC",
		lock =			"CUST_SK_Brave_Blue_ThowingDagger_AC",
		icon =			"SK_Brave_Blue_ThowingDagger_AC",
	},
	{
		id =			15,
		name =			"SK_Brave_Purple_ThowingDagger_AC",
		CustID =		"SK_Brave_Purple_ThowingDagger_AC",
		lock =			"CUST_SK_Brave_Purple_ThowingDagger_AC",
		icon =			"SK_Brave_Purple_ThowingDagger_AC",
	},
	{
		id =			16,
		name =			"SK_Brave_Green_BlowDart_AC",
		CustID =		"SK_Brave_Green_BlowDart_AC",
		lock =			"CUST_SK_Brave_Green_BlowDart_AC",
		icon =			"SK_Brave_Green_BlowDart_AC",
	},
	{
		id =			17,
		name =			"SK_Brave_Blue_BlowDart_AC",
		CustID =		"SK_Brave_Blue_BlowDart_AC",
		lock =			"CUST_SK_Brave_Blue_BlowDart_AC",
		icon =			"SK_Brave_Blue_BlowDart_AC",
	},
	{
		id =			18,
		name =			"SK_Brave_Purple_BlowDart_AC",
		CustID =		"SK_Brave_Purple_BlowDart_AC",
		lock =			"CUST_SK_Brave_Purple_BlowDart_AC",
		icon =			"SK_Brave_Purple_BlowDart_AC",
	},
	{
		id =			19,
		name =			"SK_Brave_Green_FryingPan_AC",
		CustID =		"SK_Brave_Green_FryingPan_AC",
		lock =			"CUST_SK_Brave_Green_FryingPan_AC",
		icon =			"SK_Brave_Green_FryingPan_AC",
	},
	{
		id =			20,
		name =			"SK_Brave_Blue_FryingPan_AC",
		CustID =		"SK_Brave_Blue_FryingPan_AC",
		lock =			"CUST_SK_Brave_Blue_FryingPan_AC",
		icon =			"SK_Brave_Blue_FryingPan_AC",
	},
	{
		id =			21,
		name =			"SK_Brave_Purple_FryingPan_AC",
		CustID =		"SK_Brave_Purple_FryingPan_AC",
		lock =			"CUST_SK_Brave_Purple_FryingPan_AC",
		icon =			"SK_Brave_Purple_FryingPan_AC",
	},
	{
		id =			22,
		name =			"SK_Brave_Green_Boomarang_AC",
		CustID =		"SK_Brave_Green_Boomarang_AC",
		lock =			"CUST_SK_Brave_Green_Boomarang_AC",
		icon =			"SK_Brave_Green_Boomarang_AC",
	},
	{
		id =			23,
		name =			"SK_Brave_Blue_Boomarang_AC",
		CustID =		"SK_Brave_Blue_Boomarang_AC",
		lock =			"CUST_SK_Brave_Blue_Boomarang_AC",
		icon =			"SK_Brave_Blue_Boomarang_AC",
	},
	{
		id =			24,
		name =			"SK_Brave_Purple_Boomarang_AC",
		CustID =		"SK_Brave_Purple_Boomarang_AC",
		lock =			"CUST_SK_Brave_Purple_Boomarang_AC",
		icon =			"SK_Brave_Purple_Boomarang_AC",
	},
	{
		id =			25,
		name =			"SK_Brave_Green_BowArrow_AC",
		CustID =		"SK_Brave_Green_BowArrow_AC",
		lock =			"CUST_SK_Brave_Green_BowArrow_AC",
		icon =			"SK_Brave_Green_BowArrow_AC",
	},
	{
		id =			26,
		name =			"SK_Brave_Blue_BowArrow_AC",
		CustID =		"SK_Brave_Blue_BowArrow_AC",
		lock =			"CUST_SK_Brave_Blue_BowArrow_AC",
		icon =			"SK_Brave_Blue_BowArrow_AC",
	},
	{
		id =			27,
		name =			"SK_Brave_Purple_BowArrow_AC",
		CustID =		"SK_Brave_Purple_BowArrow_AC",
		lock =			"CUST_SK_Brave_Purple_BowArrow_AC",
		icon =			"SK_Brave_Purple_BowArrow_AC",
	},
	{
		id =			28,
		name =			"SK_Brave_Green_MagicPotion_AC",
		CustID =		"SK_Brave_Green_MagicPotion_AC",
		lock =			"CUST_SK_Brave_Green_MagicPotion_AC",
		icon =			"SK_Brave_Green_MagicPotion_AC",
	},
	{
		id =			29,
		name =			"SK_Brave_Blue_MagicPotion_AC",
		CustID =		"SK_Brave_Blue_MagicPotion_AC",
		lock =			"CUST_SK_Brave_Blue_MagicPotion_AC",
		icon =			"SK_Brave_Blue_MagicPotion_AC",
	},
	{
		id =			30,
		name =			"SK_Brave_Purple_MagicPotion_AC",
		CustID =		"SK_Brave_Purple_MagicPotion_AC",
		lock =			"CUST_SK_Brave_Purple_MagicPotion_AC",
		icon =			"SK_Brave_Purple_MagicPotion_AC",
	},
	{
		id =			31,
		name =			"SK_Brave_Blue_IceCrystal_AC",
		CustID =		"SK_Brave_Blue_IceCrystal_AC",
		lock =			"CUST_SK_Brave_Blue_IceCrystal_AC",
		icon =			"SK_Brave_Blue_IceCrystal_AC",
	},
	{
		id =			32,
		name =			"SK_Brave_Purple_IceCrystal_AC",
		CustID =		"SK_Brave_Purple_IceCrystal_AC",
		lock =			"CUST_SK_Brave_Purple_IceCrystal_AC",
		icon =			"SK_Brave_Purple_IceCrystal_AC",
	},
	{
		id =			33,
		name =			"SK_Brave_Orange_IceCrystal_AC",
		CustID =		"SK_Brave_Orange_IceCrystal_AC",
		lock =			"CUST_SK_Brave_Orange_IceCrystal_AC",
		icon =			"SK_Brave_Orange_IceCrystal_AC",
	},
	{
		id =			34,
		name =			"SK_Brave_Blue_Sling_AC",
		CustID =		"SK_Brave_Blue_Sling_AC",
		lock =			"CUST_SK_Brave_Blue_Sling_AC",
		icon =			"SK_Brave_Blue_Sling_AC",
	},
	{
		id =			35,
		name =			"SK_Brave_Purple_Sling_AC",
		CustID =		"SK_Brave_Purple_Sling_AC",
		lock =			"CUST_SK_Brave_Purple_Sling_AC",
		icon =			"SK_Brave_Purple_Sling_AC",
	},
	{
		id =			36,
		name =			"SK_Brave_Orange_Sling_AC",
		CustID =		"SK_Brave_Orange_Sling_AC",
		lock =			"CUST_SK_Brave_Orange_Sling_AC",
		icon =			"SK_Brave_Orange_Sling_AC",
	},
	{
		id =			37,
		name =			"SK_Brave_Green_CelticShield_AC",
		CustID =		"SK_Brave_Green_CelticShield_AC",
		lock =			"CUST_SK_Brave_Green_CelticShield_AC",
		icon =			"SK_Brave_Green_CelticShield_AC",
	},
	{
		id =			38,
		name =			"SK_Brave_Blue_CelticShield_AC",
		CustID =		"SK_Brave_Blue_CelticShield_AC",
		lock =			"CUST_SK_Brave_Blue_CelticShield_AC",
		icon =			"SK_Brave_Blue_CelticShield_AC",
	},
	{
		id =			39,
		name =			"SK_Brave_Purple_CelticShield_AC",
		CustID =		"SK_Brave_Purple_CelticShield_AC",
		lock =			"CUST_SK_Brave_Purple_CelticShield_AC",
		icon =			"SK_Brave_Purple_CelticShield_AC",
	},
	{
		id =			40,
		name =			"SK_Brave_Green_WarHammer_AC",
		CustID =		"SK_Brave_Green_WarHammer_AC",
		lock =			"CUST_SK_Brave_Green_WarHammer_AC",
		icon =			"SK_Brave_Green_WarHammer_AC",
	},
	{
		id =			41,
		name =			"SK_Brave_Blue_WarHammer_AC",
		CustID =		"SK_Brave_Blue_WarHammer_AC",
		lock =			"CUST_SK_Brave_Blue_WarHammer_AC",
		icon =			"SK_Brave_Blue_WarHammer_AC",
	},
	{
		id =			42,
		name =			"SK_Brave_Purple_WarHammer_AC",
		CustID =		"SK_Brave_Purple_WarHammer_AC",
		lock =			"CUST_SK_Brave_Purple_WarHammer_AC",
		icon =			"SK_Brave_Purple_WarHammer_AC",
	},
	{
		id =			43,
		name =			"SK_Brave_Green_BasketMushrooms_AC",
		CustID =		"SK_Brave_Green_BasketMushrooms_AC",
		lock =			"CUST_SK_Brave_Green_BasketMushrooms_AC",
		icon =			"SK_Brave_Green_BasketMushrooms_AC",
	},
	{
		id =			44,
		name =			"SK_Brave_Blue_BasketMushrooms_AC",
		CustID =		"SK_Brave_Blue_BasketMushrooms_AC",
		lock =			"CUST_SK_Brave_Blue_BasketMushrooms_AC",
		icon =			"SK_Brave_Blue_BasketMushrooms_AC",
	},
	{
		id =			45,
		name =			"SK_Brave_Purple_BasketMushrooms_AC",
		CustID =		"SK_Brave_Purple_BasketMushrooms_AC",
		lock =			"CUST_SK_Brave_Purple_BasketMushrooms_AC",
		icon =			"SK_Brave_Purple_BasketMushrooms_AC",
	},
	{
		id =			46,
		name =			"SK_Brave_Blue_SpellBook_AC",
		CustID =		"SK_Brave_Blue_SpellBook_AC",
		lock =			"CUST_SK_Brave_Blue_SpellBook_AC",
		icon =			"SK_Brave_Blue_SpellBook_AC",
	},
	{
		id =			47,
		name =			"SK_Brave_Purple_SpellBook_AC",
		CustID =		"SK_Brave_Purple_SpellBook_AC",
		lock =			"CUST_SK_Brave_Purple_SpellBook_AC",
		icon =			"SK_Brave_Purple_SpellBook_AC",
	},
	{
		id =			48,
		name =			"SK_Brave_Orange_SpellBook_AC",
		CustID =		"SK_Brave_Orange_SpellBook_AC",
		lock =			"CUST_SK_Brave_Orange_SpellBook_AC",
		icon =			"SK_Brave_Orange_SpellBook_AC",
	},
	{
		id =			49,
		name =			"SK_Brave_Green_LeatherCap_HR",
		CustID =		"SK_Brave_Green_LeatherCap_HR",
		lock =			"CUST_SK_Brave_Green_LeatherCap_HR",
		icon =			"SK_Brave_Green_LeatherCap_HR",
	},
	{
		id =			50,
		name =			"SK_Brave_Blue_LeatherCap_HR",
		CustID =		"SK_Brave_Blue_LeatherCap_HR",
		lock =			"CUST_SK_Brave_Blue_LeatherCap_HR",
		icon =			"SK_Brave_Blue_LeatherCap_HR",
	},
	{
		id =			51,
		name =			"SK_Brave_Purple_LeatherCap_HR",
		CustID =		"SK_Brave_Purple_LeatherCap_HR",
		lock =			"CUST_SK_Brave_Purple_LeatherCap_HR",
		icon =			"SK_Brave_Purple_LeatherCap_HR",
	},
	{
		id =			52,
		name =			"SK_Brave_Green_DingedHelmet_HR",
		CustID =		"SK_Brave_Green_DingedHelmet_HR",
		lock =			"CUST_SK_Brave_Green_DingedHelmet_HR",
		icon =			"SK_Brave_Green_DingedHelmet_HR",
	},
	{
		id =			53,
		name =			"SK_Brave_Blue_DingedHelmet_HR",
		CustID =		"SK_Brave_Blue_DingedHelmet_HR",
		lock =			"CUST_SK_Brave_Blue_DingedHelmet_HR",
		icon =			"SK_Brave_Blue_DingedHelmet_HR",
	},
	{
		id =			54,
		name =			"SK_Brave_Purple_DingedHelmet_HR",
		CustID =		"SK_Brave_Purple_DingedHelmet_HR",
		lock =			"CUST_SK_Brave_Purple_DingedHelmet_HR",
		icon =			"SK_Brave_Purple_DingedHelmet_HR",
	},
	{
		id =			55,
		name =			"SK_Brave_Green_QueenCrown_HR",
		CustID =		"SK_Brave_Green_QueenCrown_HR",
		lock =			"CUST_SK_Brave_Green_QueenCrown_HR",
		icon =			"SK_Brave_Green_QueenCrown_HR",
	},
	{
		id =			56,
		name =			"SK_Brave_Blue_QueenCrown_HR",
		CustID =		"SK_Brave_Blue_QueenCrown_HR",
		lock =			"CUST_SK_Brave_Blue_QueenCrown_HR",
		icon =			"SK_Brave_Blue_QueenCrown_HR",
	},
	{
		id =			57,
		name =			"SK_Brave_Purple_QueenCrown_HR",
		CustID =		"SK_Brave_Purple_QueenCrown_HR",
		lock =			"CUST_SK_Brave_Purple_QueenCrown_HR",
		icon =			"SK_Brave_Purple_QueenCrown_HR",
	},
	{
		id =			58,
		name =			"SK_Brave_Green_ChefHat_HR",
		CustID =		"SK_Brave_Green_ChefHat_HR",
		lock =			"CUST_SK_Brave_Green_ChefHat_HR",
		icon =			"SK_Brave_Green_ChefHat_HR",
	},
	{
		id =			59,
		name =			"SK_Brave_Blue_ChefHat_HR",
		CustID =		"SK_Brave_Blue_ChefHat_HR",
		lock =			"CUST_SK_Brave_Blue_ChefHat_HR",
		icon =			"SK_Brave_Blue_ChefHat_HR",
	},
	{
		id =			60,
		name =			"SK_Brave_Purple_ChefHat_HR",
		CustID =		"SK_Brave_Purple_ChefHat_HR",
		lock =			"CUST_SK_Brave_Purple_ChefHat_HR",
		icon =			"SK_Brave_Purple_ChefHat_HR",
	},
	{
		id =			61,
		name =			"SK_Brave_Green_MeridaHair_HR",
		CustID =		"SK_Brave_Green_MeridaHair_HR",
		lock =			"CUST_SK_Brave_Green_MeridaHair_HR",
		icon =			"SK_Brave_Green_MeridaHair_HR",
	},
	{
		id =			62,
		name =			"SK_Brave_Blue_MeridaHair_HR",
		CustID =		"SK_Brave_Blue_MeridaHair_HR",
		lock =			"CUST_SK_Brave_Blue_MeridaHair_HR",
		icon =			"SK_Brave_Blue_MeridaHair_HR",
	},
	{
		id =			63,
		name =			"SK_Brave_Purple_MeridaHair_HR",
		CustID =		"SK_Brave_Purple_MeridaHair_HR",
		lock =			"CUST_SK_Brave_Purple_MeridaHair_HR",
		icon =			"SK_Brave_Purple_MeridaHair_HR",
	},
	{
		id =			64,
		name =			"SK_Brave_Green_MeridaHood_HR",
		CustID =		"SK_Brave_Green_MeridaHood_HR",
		lock =			"CUST_SK_Brave_Green_MeridaHood_HR",
		icon =			"SK_Brave_Green_MeridaHood_HR",
	},
	{
		id =			65,
		name =			"SK_Brave_Blue_MeridaHood_HR",
		CustID =		"SK_Brave_Blue_MeridaHood_HR",
		lock =			"CUST_SK_Brave_Blue_MeridaHood_HR",
		icon =			"SK_Brave_Blue_MeridaHood_HR",
	},
	{
		id =			66,
		name =			"SK_Brave_Purple_MeridaHood_HR",
		CustID =		"SK_Brave_Purple_MeridaHood_HR",
		lock =			"CUST_SK_Brave_Purple_MeridaHood_HR",
		icon =			"SK_Brave_Purple_MeridaHood_HR",
	},
	{
		id =			67,
		name =			"SK_Brave_Green_WeldingMask_HR",
		CustID =		"SK_Brave_Green_WeldingMask_HR",
		lock =			"CUST_SK_Brave_Green_WeldingMask_HR",
		icon =			"SK_Brave_Green_WeldingMask_HR",
	},
	{
		id =			68,
		name =			"SK_Brave_Blue_WeldingMask_HR",
		CustID =		"SK_Brave_Blue_WeldingMask_HR",
		lock =			"CUST_SK_Brave_Blue_WeldingMask_HR",
		icon =			"SK_Brave_Blue_WeldingMask_HR",
	},
	{
		id =			69,
		name =			"SK_Brave_Purple_WeldingMask_HR",
		CustID =		"SK_Brave_Purple_WeldingMask_HR",
		lock =			"CUST_SK_Brave_Purple_WeldingMask_HR",
		icon =			"SK_Brave_Purple_WeldingMask_HR",
	},
	{
		id =			70,
		name =			"SK_Brave_Green_WitchsHair_HR",
		CustID =		"SK_Brave_Green_WitchsHair_HR",
		lock =			"CUST_SK_Brave_Green_WitchsHair_HR",
		icon =			"SK_Brave_Green_WitchsHair_HR",
	},
	{
		id =			71,
		name =			"SK_Brave_Blue_WitchsHair_HR",
		CustID =		"SK_Brave_Blue_WitchsHair_HR",
		lock =			"CUST_SK_Brave_Blue_WitchsHair_HR",
		icon =			"SK_Brave_Blue_WitchsHair_HR",
	},
	{
		id =			72,
		name =			"SK_Brave_Purple_WitchsHair_HR",
		CustID =		"SK_Brave_Purple_WitchsHair_HR",
		lock =			"CUST_SK_Brave_Purple_WitchsHair_HR",
		icon =			"SK_Brave_Purple_WitchsHair_HR",
	},
	{
		id =			73,
		name =			"SK_Brave_Green_Dunbroch_HR",
		CustID =		"SK_Brave_Green_Dunbroch_HR",
		lock =			"CUST_SK_Brave_Green_Dunbroch_HR",
		icon =			"SK_Brave_Green_Dunbroch_HR",
	},
	{
		id =			74,
		name =			"SK_Brave_Blue_Dunbroch_HR",
		CustID =		"SK_Brave_Blue_Dunbroch_HR",
		lock =			"CUST_SK_Brave_Blue_Dunbroch_HR",
		icon =			"SK_Brave_Blue_Dunbroch_HR",
	},
	{
		id =			75,
		name =			"SK_Brave_Purple_Dunbroch_HR",
		CustID =		"SK_Brave_Purple_Dunbroch_HR",
		lock =			"CUST_SK_Brave_Purple_Dunbroch_HR",
		icon =			"SK_Brave_Purple_Dunbroch_HR",
	},
	{
		id =			76,
		name =			"SK_Brave_Blue_Dingwall_HR",
		CustID =		"SK_Brave_Blue_Dingwall_HR",
		lock =			"CUST_SK_Brave_Blue_Dingwall_HR",
		icon =			"SK_Brave_Blue_Dingwall_HR",
	},
	{
		id =			77,
		name =			"SK_Brave_Purple_Dingwall_HR",
		CustID =		"SK_Brave_Purple_Dingwall_HR",
		lock =			"CUST_SK_Brave_Purple_Dingwall_HR",
		icon =			"SK_Brave_Purple_Dingwall_HR",
	},
	{
		id =			78,
		name =			"SK_Brave_Orange_Dingwall_HR",
		CustID =		"SK_Brave_Orange_Dingwall_HR",
		lock =			"CUST_SK_Brave_Orange_Dingwall_HR",
		icon =			"SK_Brave_Orange_Dingwall_HR",
	},
	{
		id =			79,
		name =			"SK_Brave_Blue_Macintosh_HR",
		CustID =		"SK_Brave_Blue_Macintosh_HR",
		lock =			"CUST_SK_Brave_Blue_Macintosh_HR",
		icon =			"SK_Brave_Blue_Macintosh_HR",
	},
	{
		id =			80,
		name =			"SK_Brave_Purple_Macintosh_HR",
		CustID =		"SK_Brave_Purple_Macintosh_HR",
		lock =			"CUST_SK_Brave_Purple_Macintosh_HR",
		icon =			"SK_Brave_Purple_Macintosh_HR",
	},
	{
		id =			81,
		name =			"SK_Brave_Orange_Macintosh_HR",
		CustID =		"SK_Brave_Orange_Macintosh_HR",
		lock =			"CUST_SK_Brave_Orange_Macintosh_HR",
		icon =			"SK_Brave_Orange_Macintosh_HR",
	},
	{
		id =			82,
		name =			"SK_Brave_Green_HelmetMacGuffin_HR",
		CustID =		"SK_Brave_Green_HelmetMacGuffin_HR",
		lock =			"CUST_SK_Brave_Green_HelmetMacGuffin_HR",
		icon =			"SK_Brave_Green_HelmetMacGuffin_HR",
	},
	{
		id =			83,
		name =			"SK_Brave_Blue_HelmetMacGuffin_HR",
		CustID =		"SK_Brave_Blue_HelmetMacGuffin_HR",
		lock =			"CUST_SK_Brave_Blue_HelmetMacGuffin_HR",
		icon =			"SK_Brave_Blue_HelmetMacGuffin_HR",
	},
	{
		id =			84,
		name =			"SK_Brave_Purple_HelmetMacGuffin_HR",
		CustID =		"SK_Brave_Purple_HelmetMacGuffin_HR",
		lock =			"CUST_SK_Brave_Purple_HelmetMacGuffin_HR",
		icon =			"SK_Brave_Purple_HelmetMacGuffin_HR",
	},
	{
		id =			85,
		name =			"SK_Brave_Green_HornedHelmet_HR",
		CustID =		"SK_Brave_Green_HornedHelmet_HR",
		lock =			"CUST_SK_Brave_Green_HornedHelmet_HR",
		icon =			"SK_Brave_Green_HornedHelmet_HR",
	},
	{
		id =			86,
		name =			"SK_Brave_Blue_HornedHelmet_HR",
		CustID =		"SK_Brave_Blue_HornedHelmet_HR",
		lock =			"CUST_SK_Brave_Blue_HornedHelmet_HR",
		icon =			"SK_Brave_Blue_HornedHelmet_HR",
	},
	{
		id =			87,
		name =			"SK_Brave_Purple_HornedHelmet_HR",
		CustID =		"SK_Brave_Purple_HornedHelmet_HR",
		lock =			"CUST_SK_Brave_Purple_HornedHelmet_HR",
		icon =			"SK_Brave_Purple_HornedHelmet_HR",
	},
	{
		id =			88,
		name =			"SK_Brave_Green_WingedHelm_HR",
		CustID =		"SK_Brave_Green_WingedHelm_HR",
		lock =			"CUST_SK_Brave_Green_WingedHelm_HR",
		icon =			"SK_Brave_Green_WingedHelm_HR",
	},
	{
		id =			89,
		name =			"SK_Brave_Blue_WingedHelm_HR",
		CustID =		"SK_Brave_Blue_WingedHelm_HR",
		lock =			"CUST_SK_Brave_Blue_WingedHelm_HR",
		icon =			"SK_Brave_Blue_WingedHelm_HR",
	},
	{
		id =			90,
		name =			"SK_Brave_Purple_WingedHelm_HR",
		CustID =		"SK_Brave_Purple_WingedHelm_HR",
		lock =			"CUST_SK_Brave_Purple_WingedHelm_HR",
		icon =			"SK_Brave_Purple_WingedHelm_HR",
	},
	{
		id =			91,
		name =			"SK_Brave_Blue_GreatHelm_HR",
		CustID =		"SK_Brave_Blue_GreatHelm_HR",
		lock =			"CUST_SK_Brave_Blue_GreatHelm_HR",
		icon =			"SK_Brave_Blue_GreatHelm_HR",
	},
	{
		id =			92,
		name =			"SK_Brave_Purple_GreatHelm_HR",
		CustID =		"SK_Brave_Purple_GreatHelm_HR",
		lock =			"CUST_SK_Brave_Purple_GreatHelm_HR",
		icon =			"SK_Brave_Purple_GreatHelm_HR",
	},
	{
		id =			93,
		name =			"SK_Brave_Orange_GreatHelm_HR",
		CustID =		"SK_Brave_Orange_GreatHelm_HR",
		lock =			"CUST_SK_Brave_Orange_GreatHelm_HR",
		icon =			"SK_Brave_Orange_GreatHelm_HR",
	},
	{
		id =			94,
		name =			"SK_Brave_Green_ArmorBasic1_B",
		CustID =		"SK_Brave_Green_ArmorBasic1_B",
		lock =			"CUST_SK_Brave_Green_ArmorBasic1_B",
		icon =			"SK_Brave_Green_ArmorBasic1_B",
	},
	{
		id =			95,
		name =			"SK_Brave_Blue_ArmorBasic1_B",
		CustID =		"SK_Brave_Blue_ArmorBasic1_B",
		lock =			"CUST_SK_Brave_Blue_ArmorBasic1_B",
		icon =			"SK_Brave_Blue_ArmorBasic1_B",
	},
	{
		id =			96,
		name =			"SK_Brave_Purple_ArmorBasic1_B",
		CustID =		"SK_Brave_Purple_ArmorBasic1_B",
		lock =			"CUST_SK_Brave_Purple_ArmorBasic1_B",
		icon =			"SK_Brave_Purple_ArmorBasic1_B",
	},
	{
		id =			97,
		name =			"SK_Brave_Green_ArmorBasic2_B",
		CustID =		"SK_Brave_Green_ArmorBasic2_B",
		lock =			"CUST_SK_Brave_Green_ArmorBasic2_B",
		icon =			"SK_Brave_Green_ArmorBasic2_B",
	},
	{
		id =			98,
		name =			"SK_Brave_Blue_ArmorBasic2_B",
		CustID =		"SK_Brave_Blue_ArmorBasic2_B",
		lock =			"CUST_SK_Brave_Blue_ArmorBasic2_B",
		icon =			"SK_Brave_Blue_ArmorBasic2_B",
	},
	{
		id =			99,
		name =			"SK_Brave_Purple_ArmorBasic2_B",
		CustID =		"SK_Brave_Purple_ArmorBasic2_B",
		lock =			"CUST_SK_Brave_Purple_ArmorBasic2_B",
		icon =			"SK_Brave_Purple_ArmorBasic2_B",
	},
	{
		id =			100,
		name =			"SK_Brave_Green_ArmorBasic3_B",
		CustID =		"SK_Brave_Green_ArmorBasic3_B",
		lock =			"CUST_SK_Brave_Green_ArmorBasic3_B",
		icon =			"SK_Brave_Green_ArmorBasic3_B",
	},
	{
		id =			101,
		name =			"SK_Brave_Blue_ArmorBasic3_B",
		CustID =		"SK_Brave_Blue_ArmorBasic3_B",
		lock =			"CUST_SK_Brave_Blue_ArmorBasic3_B",
		icon =			"SK_Brave_Blue_ArmorBasic3_B",
	},
	{
		id =			102,
		name =			"SK_Brave_Purple_ArmorBasic3_B",
		CustID =		"SK_Brave_Purple_ArmorBasic3_B",
		lock =			"CUST_SK_Brave_Purple_ArmorBasic3_B",
		icon =			"SK_Brave_Purple_ArmorBasic3_B",
	},
	{
		id =			103,
		name =			"SK_Brave_Green_ArmorBasic4_B",
		CustID =		"SK_Brave_Green_ArmorBasic4_B",
		lock =			"CUST_SK_Brave_Green_ArmorBasic4_B",
		icon =			"SK_Brave_Green_ArmorBasic4_B",
	},
	{
		id =			104,
		name =			"SK_Brave_Blue_ArmorBasic4_B",
		CustID =		"SK_Brave_Blue_ArmorBasic4_B",
		lock =			"CUST_SK_Brave_Blue_ArmorBasic4_B",
		icon =			"SK_Brave_Blue_ArmorBasic4_B",
	},
	{
		id =			105,
		name =			"SK_Brave_Purple_ArmorBasic4_B",
		CustID =		"SK_Brave_Purple_ArmorBasic4_B",
		lock =			"CUST_SK_Brave_Purple_ArmorBasic4_B",
		icon =			"SK_Brave_Purple_ArmorBasic4_B",
	},
	{
		id =			106,
		name =			"SK_Brave_Green_ArmorBasic5_B",
		CustID =		"SK_Brave_Green_ArmorBasic5_B",
		lock =			"CUST_SK_Brave_Green_ArmorBasic5_B",
		icon =			"SK_Brave_Green_ArmorBasic5_B",
	},
	{
		id =			107,
		name =			"SK_Brave_Blue_ArmorBasic5_B",
		CustID =		"SK_Brave_Blue_ArmorBasic5_B",
		lock =			"CUST_SK_Brave_Blue_ArmorBasic5_B",
		icon =			"SK_Brave_Blue_ArmorBasic5_B",
	},
	{
		id =			108,
		name =			"SK_Brave_Purple_ArmorBasic5_B",
		CustID =		"SK_Brave_Purple_ArmorBasic5_B",
		lock =			"CUST_SK_Brave_Purple_ArmorBasic5_B",
		icon =			"SK_Brave_Purple_ArmorBasic5_B",
	},
	{
		id =			109,
		name =			"SK_Brave_Green_ArmorStandard1_B",
		CustID =		"SK_Brave_Green_ArmorStandard1_B",
		lock =			"CUST_SK_Brave_Green_ArmorStandard1_B",
		icon =			"SK_Brave_Green_ArmorStandard1_B",
	},
	{
		id =			110,
		name =			"SK_Brave_Blue_ArmorStandard1_B",
		CustID =		"SK_Brave_Blue_ArmorStandard1_B",
		lock =			"CUST_SK_Brave_Blue_ArmorStandard1_B",
		icon =			"SK_Brave_Blue_ArmorStandard1_B",
	},
	{
		id =			111,
		name =			"SK_Brave_Purple_ArmorStandard1_B",
		CustID =		"SK_Brave_Purple_ArmorStandard1_B",
		lock =			"CUST_SK_Brave_Purple_ArmorStandard1_B",
		icon =			"SK_Brave_Purple_ArmorStandard1_B",
	},
	{
		id =			112,
		name =			"SK_Brave_Green_ArmorStandard2_B",
		CustID =		"SK_Brave_Green_ArmorStandard2_B",
		lock =			"CUST_SK_Brave_Green_ArmorStandard2_B",
		icon =			"SK_Brave_Green_ArmorStandard2_B",
	},
	{
		id =			113,
		name =			"SK_Brave_Blue_ArmorStandard2_B",
		CustID =		"SK_Brave_Blue_ArmorStandard2_B",
		lock =			"CUST_SK_Brave_Blue_ArmorStandard2_B",
		icon =			"SK_Brave_Blue_ArmorStandard2_B",
	},
	{
		id =			114,
		name =			"SK_Brave_Purple_ArmorStandard2_B",
		CustID =		"SK_Brave_Purple_ArmorStandard2_B",
		lock =			"CUST_SK_Brave_Purple_ArmorStandard2_B",
		icon =			"SK_Brave_Purple_ArmorStandard2_B",
	},
	{
		id =			115,
		name =			"SK_Brave_Green_ArmorStandard3_B",
		CustID =		"SK_Brave_Green_ArmorStandard3_B",
		lock =			"CUST_SK_Brave_Green_ArmorStandard3_B",
		icon =			"SK_Brave_Green_ArmorStandard3_B",
	},
	{
		id =			116,
		name =			"SK_Brave_Blue_ArmorStandard3_B",
		CustID =		"SK_Brave_Blue_ArmorStandard3_B",
		lock =			"CUST_SK_Brave_Blue_ArmorStandard3_B",
		icon =			"SK_Brave_Blue_ArmorStandard3_B",
	},
	{
		id =			117,
		name =			"SK_Brave_Purple_ArmorStandard3_B",
		CustID =		"SK_Brave_Purple_ArmorStandard3_B",
		lock =			"CUST_SK_Brave_Purple_ArmorStandard3_B",
		icon =			"SK_Brave_Purple_ArmorStandard3_B",
	},
	{
		id =			118,
		name =			"SK_Brave_Green_ArmorStandard4_B",
		CustID =		"SK_Brave_Green_ArmorStandard4_B",
		lock =			"CUST_SK_Brave_Green_ArmorStandard4_B",
		icon =			"SK_Brave_Green_ArmorStandard4_B",
	},
	{
		id =			119,
		name =			"SK_Brave_Blue_ArmorStandard4_B",
		CustID =		"SK_Brave_Blue_ArmorStandard4_B",
		lock =			"CUST_SK_Brave_Blue_ArmorStandard4_B",
		icon =			"SK_Brave_Blue_ArmorStandard4_B",
	},
	{
		id =			120,
		name =			"SK_Brave_Purple_ArmorStandard4_B",
		CustID =		"SK_Brave_Purple_ArmorStandard4_B",
		lock =			"CUST_SK_Brave_Purple_ArmorStandard4_B",
		icon =			"SK_Brave_Purple_ArmorStandard4_B",
	},
	{
		id =			121,
		name =			"SK_Brave_Blue_ArmorStandard5_B",
		CustID =		"SK_Brave_Blue_ArmorStandard5_B",
		lock =			"CUST_SK_Brave_Blue_ArmorStandard5_B",
		icon =			"SK_Brave_Blue_ArmorStandard5_B",
	},
	{
		id =			122,
		name =			"SK_Brave_Purple_ArmorStandard5_B",
		CustID =		"SK_Brave_Purple_ArmorStandard5_B",
		lock =			"CUST_SK_Brave_Purple_ArmorStandard5_B",
		icon =			"SK_Brave_Purple_ArmorStandard5_B",
	},
	{
		id =			123,
		name =			"SK_Brave_Orange_ArmorStandard5_B",
		CustID =		"SK_Brave_Orange_ArmorStandard5_B",
		lock =			"CUST_SK_Brave_Orange_ArmorStandard5_B",
		icon =			"SK_Brave_Orange_ArmorStandard5_B",
	},
	{
		id =			124,
		name =			"SK_Brave_Blue_ArmorAdvanced1_B",
		CustID =		"SK_Brave_Blue_ArmorAdvanced1_B",
		lock =			"CUST_SK_Brave_Blue_ArmorAdvanced1_B",
		icon =			"SK_Brave_Blue_ArmorAdvanced1_B",
	},
	{
		id =			125,
		name =			"SK_Brave_Purple_ArmorAdvanced1_B",
		CustID =		"SK_Brave_Purple_ArmorAdvanced1_B",
		lock =			"CUST_SK_Brave_Purple_ArmorAdvanced1_B",
		icon =			"SK_Brave_Purple_ArmorAdvanced1_B",
	},
	{
		id =			126,
		name =			"SK_Brave_Orange_ArmorAdvanced1_B",
		CustID =		"SK_Brave_Orange_ArmorAdvanced1_B",
		lock =			"CUST_SK_Brave_Orange_ArmorAdvanced1_B",
		icon =			"SK_Brave_Orange_ArmorAdvanced1_B",
	},
	{
		id =			127,
		name =			"SK_Brave_Green_ArmorAdvanced2_B",
		CustID =		"SK_Brave_Green_ArmorAdvanced2_B",
		lock =			"CUST_SK_Brave_Green_ArmorAdvanced2_B",
		icon =			"SK_Brave_Green_ArmorAdvanced2_B",
	},
	{
		id =			128,
		name =			"SK_Brave_Blue_ArmorAdvanced2_B",
		CustID =		"SK_Brave_Blue_ArmorAdvanced2_B",
		lock =			"CUST_SK_Brave_Blue_ArmorAdvanced2_B",
		icon =			"SK_Brave_Blue_ArmorAdvanced2_B",
	},
	{
		id =			129,
		name =			"SK_Brave_Purple_ArmorAdvanced2_B",
		CustID =		"SK_Brave_Purple_ArmorAdvanced2_B",
		lock =			"CUST_SK_Brave_Purple_ArmorAdvanced2_B",
		icon =			"SK_Brave_Purple_ArmorAdvanced2_B",
	},
	{
		id =			130,
		name =			"SK_Brave_Green_ArmorAdvanced3_B",
		CustID =		"SK_Brave_Green_ArmorAdvanced3_B",
		lock =			"CUST_SK_Brave_Green_ArmorAdvanced3_B",
		icon =			"SK_Brave_Green_ArmorAdvanced3_B",
	},
	{
		id =			131,
		name =			"SK_Brave_Blue_ArmorAdvanced3_B",
		CustID =		"SK_Brave_Blue_ArmorAdvanced3_B",
		lock =			"CUST_SK_Brave_Blue_ArmorAdvanced3_B",
		icon =			"SK_Brave_Blue_ArmorAdvanced3_B",
	},
	{
		id =			132,
		name =			"SK_Brave_Purple_ArmorAdvanced3_B",
		CustID =		"SK_Brave_Purple_ArmorAdvanced3_B",
		lock =			"CUST_SK_Brave_Purple_ArmorAdvanced3_B",
		icon =			"SK_Brave_Purple_ArmorAdvanced3_B",
	},
	{
		id =			133,
		name =			"SK_Brave_Green_ArmorAdvanced4_B",
		CustID =		"SK_Brave_Green_ArmorAdvanced4_B",
		lock =			"CUST_SK_Brave_Green_ArmorAdvanced4_B",
		icon =			"SK_Brave_Green_ArmorAdvanced4_B",
	},
	{
		id =			134,
		name =			"SK_Brave_Blue_ArmorAdvanced4_B",
		CustID =		"SK_Brave_Blue_ArmorAdvanced4_B",
		lock =			"CUST_SK_Brave_Blue_ArmorAdvanced4_B",
		icon =			"SK_Brave_Blue_ArmorAdvanced4_B",
	},
	{
		id =			135,
		name =			"SK_Brave_Purple_ArmorAdvanced4_B",
		CustID =		"SK_Brave_Purple_ArmorAdvanced4_B",
		lock =			"CUST_SK_Brave_Purple_ArmorAdvanced4_B",
		icon =			"SK_Brave_Purple_ArmorAdvanced4_B",
	},
	{
		id =			136,
		name =			"SK_Brave_Blue_ArmorAdvanced5_B",
		CustID =		"SK_Brave_Blue_ArmorAdvanced5_B",
		lock =			"CUST_SK_Brave_Blue_ArmorAdvanced5_B",
		icon =			"SK_Brave_Blue_ArmorAdvanced5_B",
	},
	{
		id =			137,
		name =			"SK_Brave_Purple_ArmorAdvanced5_B",
		CustID =		"SK_Brave_Purple_ArmorAdvanced5_B",
		lock =			"CUST_SK_Brave_Purple_ArmorAdvanced5_B",
		icon =			"SK_Brave_Purple_ArmorAdvanced5_B",
	},
	{
		id =			138,
		name =			"SK_Brave_Orange_ArmorAdvanced5_B",
		CustID =		"SK_Brave_Orange_ArmorAdvanced5_B",
		lock =			"CUST_SK_Brave_Orange_ArmorAdvanced5_B",
		icon =			"SK_Brave_Orange_ArmorAdvanced5_B",
	},
	{
		id =			139,
		name =			"SK_Kyln_Green_Healing_AC",
		CustID =		"SK_Kyln_Green_Healing_AC",
		lock =			"CUST_SK_Kyln_Green_Healing_AC",
		icon =			"SK_Kyln_Green_Healing_AC",
	},
	{
		id =			140,
		name =			"SK_Kyln_Blue_Healing_AC",
		CustID =		"SK_Kyln_Blue_Healing_AC",
		lock =			"CUST_SK_Kyln_Blue_Healing_AC",
		icon =			"SK_Kyln_Blue_Healing_AC",
	},
	{
		id =			141,
		name =			"SK_Kyln_Purple_Healing_AC",
		CustID =		"SK_Kyln_Purple_Healing_AC",
		lock =			"CUST_SK_Kyln_Purple_Healing_AC",
		icon =			"SK_Kyln_Purple_Healing_AC",
	},
	{
		id =			142,
		name =			"SK_Kyln_Green_Blaster_AC",
		CustID =		"SK_Kyln_Green_Blaster_AC",
		lock =			"CUST_SK_Kyln_Green_Blaster_AC",
		icon =			"SK_Kyln_Green_Blaster_AC",
	},
	{
		id =			143,
		name =			"SK_Kyln_Blue_Blaster_AC",
		CustID =		"SK_Kyln_Blue_Blaster_AC",
		lock =			"CUST_SK_Kyln_Blue_Blaster_AC",
		icon =			"SK_Kyln_Blue_Blaster_AC",
	},
	{
		id =			144,
		name =			"SK_Kyln_Orange_Blaster_AC",
		CustID =		"SK_Kyln_Orange_Blaster_AC",
		lock =			"CUST_SK_Kyln_Orange_Blaster_AC",
		icon =			"SK_Kyln_Orange_Blaster_AC",
	},
	{
		id =			145,
		name =			"SK_Kyln_Green_EnergyHarpoon_AC",
		CustID =		"SK_Kyln_Green_EnergyHarpoon_AC",
		lock =			"CUST_SK_Kyln_Green_EnergyHarpoon_AC",
		icon =			"SK_Kyln_Green_EnergyHarpoon_AC",
	},
	{
		id =			146,
		name =			"SK_Kyln_Blue_EnergyHarpoon_AC",
		CustID =		"SK_Kyln_Blue_EnergyHarpoon_AC",
		lock =			"CUST_SK_Kyln_Blue_EnergyHarpoon_AC",
		icon =			"SK_Kyln_Blue_EnergyHarpoon_AC",
	},
	{
		id =			147,
		name =			"SK_Kyln_Purple_EnergyHarpoon_AC",
		CustID =		"SK_Kyln_Purple_EnergyHarpoon_AC",
		lock =			"CUST_SK_Kyln_Purple_EnergyHarpoon_AC",
		icon =			"SK_Kyln_Purple_EnergyHarpoon_AC",
	},
	{
		id =			148,
		name =			"SK_Kyln_Green_LaserBeam_AC",
		CustID =		"SK_Kyln_Green_LaserBeam_AC",
		lock =			"CUST_SK_Kyln_Green_LaserBeam_AC",
		icon =			"SK_Kyln_Green_LaserBeam_AC",
	},
	{
		id =			149,
		name =			"SK_Kyln_Blue_LaserBeam_AC",
		CustID =		"SK_Kyln_Blue_LaserBeam_AC",
		lock =			"CUST_SK_Kyln_Blue_LaserBeam_AC",
		icon =			"SK_Kyln_Blue_LaserBeam_AC",
	},
	{
		id =			150,
		name =			"SK_Kyln_Purple_LaserBeam_AC",
		CustID =		"SK_Kyln_Purple_LaserBeam_AC",
		lock =			"CUST_SK_Kyln_Purple_LaserBeam_AC",
		icon =			"SK_Kyln_Purple_LaserBeam_AC",
	},
	{
		id =			151,
		name =			"SK_Kyln_Green_EnergyShuriken_AC",
		CustID =		"SK_Kyln_Green_EnergyShuriken_AC",
		lock =			"CUST_SK_Kyln_Green_EnergyShuriken_AC",
		icon =			"SK_Kyln_Green_EnergyShuriken_AC",
	},
	{
		id =			152,
		name =			"SK_Kyln_Blue_EnergyShuriken_AC",
		CustID =		"SK_Kyln_Blue_EnergyShuriken_AC",
		lock =			"CUST_SK_Kyln_Blue_EnergyShuriken_AC",
		icon =			"SK_Kyln_Blue_EnergyShuriken_AC",
	},
	{
		id =			153,
		name =			"SK_Kyln_Purple_EnergyShuriken_AC",
		CustID =		"SK_Kyln_Purple_EnergyShuriken_AC",
		lock =			"CUST_SK_Kyln_Purple_EnergyShuriken_AC",
		icon =			"SK_Kyln_Purple_EnergyShuriken_AC",
	},
	{
		id =			154,
		name =			"SK_Kyln_Green_MachineGun_AC",
		CustID =		"SK_Kyln_Green_MachineGun_AC",
		lock =			"CUST_SK_Kyln_Green_MachineGun_AC",
		icon =			"SK_Kyln_Green_MachineGun_AC",
	},
	{
		id =			155,
		name =			"SK_Kyln_Blue_MachineGun_AC",
		CustID =		"SK_Kyln_Blue_MachineGun_AC",
		lock =			"CUST_SK_Kyln_Blue_MachineGun_AC",
		icon =			"SK_Kyln_Blue_MachineGun_AC",
	},
	{
		id =			156,
		name =			"SK_Kyln_Purple_MachineGun_AC",
		CustID =		"SK_Kyln_Purple_MachineGun_AC",
		lock =			"CUST_SK_Kyln_Purple_MachineGun_AC",
		icon =			"SK_Kyln_Purple_MachineGun_AC",
	},
	{
		id =			157,
		name =			"SK_Kyln_Green_Boomarang_AC",
		CustID =		"SK_Kyln_Green_Boomarang_AC",
		lock =			"CUST_SK_Kyln_Green_Boomarang_AC",
		icon =			"SK_Kyln_Green_Boomarang_AC",
	},
	{
		id =			158,
		name =			"SK_Kyln_Blue_Boomarang_AC",
		CustID =		"SK_Kyln_Blue_Boomarang_AC",
		lock =			"CUST_SK_Kyln_Blue_Boomarang_AC",
		icon =			"SK_Kyln_Blue_Boomarang_AC",
	},
	{
		id =			159,
		name =			"SK_Kyln_Purple_Boomarang_AC",
		CustID =		"SK_Kyln_Purple_Boomarang_AC",
		lock =			"CUST_SK_Kyln_Purple_Boomarang_AC",
		icon =			"SK_Kyln_Purple_Boomarang_AC",
	},
	{
		id =			160,
		name =			"SK_Kyln_Green_RicochetDisc_AC",
		CustID =		"SK_Kyln_Green_RicochetDisc_AC",
		lock =			"CUST_SK_Kyln_Green_RicochetDisc_AC",
		icon =			"SK_Kyln_Green_RicochetDisc_AC",
	},
	{
		id =			161,
		name =			"SK_Kyln_Blue_RicochetDisc_AC",
		CustID =		"SK_Kyln_Blue_RicochetDisc_AC",
		lock =			"CUST_SK_Kyln_Blue_RicochetDisc_AC",
		icon =			"SK_Kyln_Blue_RicochetDisc_AC",
	},
	{
		id =			162,
		name =			"SK_Kyln_Purple_RicochetDisc_AC",
		CustID =		"SK_Kyln_Purple_RicochetDisc_AC",
		lock =			"CUST_SK_Kyln_Purple_RicochetDisc_AC",
		icon =			"SK_Kyln_Purple_RicochetDisc_AC",
	},
	{
		id =			163,
		name =			"SK_Kyln_Green_EnergyBow_AC",
		CustID =		"SK_Kyln_Green_EnergyBow_AC",
		lock =			"CUST_SK_Kyln_Green_EnergyBow_AC",
		icon =			"SK_Kyln_Green_EnergyBow_AC",
	},
	{
		id =			164,
		name =			"SK_Kyln_Blue_EnergyBow_AC",
		CustID =		"SK_Kyln_Blue_EnergyBow_AC",
		lock =			"CUST_SK_Kyln_Blue_EnergyBow_AC",
		icon =			"SK_Kyln_Blue_EnergyBow_AC",
	},
	{
		id =			165,
		name =			"SK_Kyln_Purple_EnergyBow_AC",
		CustID =		"SK_Kyln_Purple_EnergyBow_AC",
		lock =			"CUST_SK_Kyln_Purple_EnergyBow_AC",
		icon =			"SK_Kyln_Purple_EnergyBow_AC",
	},
	{
		id =			166,
		name =			"SK_Kyln_Green_RocketLauncher_AC",
		CustID =		"SK_Kyln_Green_RocketLauncher_AC",
		lock =			"CUST_SK_Kyln_Green_RocketLauncher_AC",
		icon =			"SK_Kyln_Green_RocketLauncher_AC",
	},
	{
		id =			167,
		name =			"SK_Kyln_Blue_RocketLauncher_AC",
		CustID =		"SK_Kyln_Blue_RocketLauncher_AC",
		lock =			"CUST_SK_Kyln_Blue_RocketLauncher_AC",
		icon =			"SK_Kyln_Blue_RocketLauncher_AC",
	},
	{
		id =			168,
		name =			"SK_Kyln_Purple_RocketLauncher_AC",
		CustID =		"SK_Kyln_Purple_RocketLauncher_AC",
		lock =			"CUST_SK_Kyln_Purple_RocketLauncher_AC",
		icon =			"SK_Kyln_Purple_RocketLauncher_AC",
	},
	{
		id =			169,
		name =			"SK_Kyln_Blue_FreezeBomb_AC",
		CustID =		"SK_Kyln_Blue_FreezeBomb_AC",
		lock =			"CUST_SK_Kyln_Blue_FreezeBomb_AC",
		icon =			"SK_Kyln_Blue_FreezeBomb_AC",
	},
	{
		id =			170,
		name =			"SK_Kyln_Purple_FreezeBomb_AC",
		CustID =		"SK_Kyln_Purple_FreezeBomb_AC",
		lock =			"CUST_SK_Kyln_Purple_FreezeBomb_AC",
		icon =			"SK_Kyln_Purple_FreezeBomb_AC",
	},
	{
		id =			171,
		name =			"SK_Kyln_Orange_FreezeBomb_AC",
		CustID =		"SK_Kyln_Orange_FreezeBomb_AC",
		lock =			"CUST_SK_Kyln_Orange_FreezeBomb_AC",
		icon =			"SK_Kyln_Orange_FreezeBomb_AC",
	},
	{
		id =			172,
		name =			"SK_Kyln_Blue_GrenadeLauncher_AC",
		CustID =		"SK_Kyln_Blue_GrenadeLauncher_AC",
		lock =			"CUST_SK_Kyln_Blue_GrenadeLauncher_AC",
		icon =			"SK_Kyln_Blue_GrenadeLauncher_AC",
	},
	{
		id =			173,
		name =			"SK_Kyln_Purple_GrenadeLauncher_AC",
		CustID =		"SK_Kyln_Purple_GrenadeLauncher_AC",
		lock =			"CUST_SK_Kyln_Purple_GrenadeLauncher_AC",
		icon =			"SK_Kyln_Purple_GrenadeLauncher_AC",
	},
	{
		id =			174,
		name =			"SK_Kyln_Orange_GrenadeLauncher_AC",
		CustID =		"SK_Kyln_Orange_GrenadeLauncher_AC",
		lock =			"CUST_SK_Kyln_Orange_GrenadeLauncher_AC",
		icon =			"SK_Kyln_Orange_GrenadeLauncher_AC",
	},
	{
		id =			175,
		name =			"SK_Kyln_Green_RiotEnergyShield_AC",
		CustID =		"SK_Kyln_Green_RiotEnergyShield_AC",
		lock =			"CUST_SK_Kyln_Green_RiotEnergyShield_AC",
		icon =			"SK_Kyln_Green_RiotEnergyShield_AC",
	},
	{
		id =			176,
		name =			"SK_Kyln_Blue_RiotEnergyShield_AC",
		CustID =		"SK_Kyln_Blue_RiotEnergyShield_AC",
		lock =			"CUST_SK_Kyln_Blue_RiotEnergyShield_AC",
		icon =			"SK_Kyln_Blue_RiotEnergyShield_AC",
	},
	{
		id =			177,
		name =			"SK_Kyln_Purple_RiotEnergyShield_AC",
		CustID =		"SK_Kyln_Purple_RiotEnergyShield_AC",
		lock =			"CUST_SK_Kyln_Purple_RiotEnergyShield_AC",
		icon =			"SK_Kyln_Purple_RiotEnergyShield_AC",
	},
	{
		id =			178,
		name =			"SK_Kyln_Green_EnergyHammer_AC",
		CustID =		"SK_Kyln_Green_EnergyHammer_AC",
		lock =			"CUST_SK_Kyln_Green_EnergyHammer_AC",
		icon =			"SK_Kyln_Green_EnergyHammer_AC",
	},
	{
		id =			179,
		name =			"SK_Kyln_Blue_EnergyHammer_AC",
		CustID =		"SK_Kyln_Blue_EnergyHammer_AC",
		lock =			"CUST_SK_Kyln_Blue_EnergyHammer_AC",
		icon =			"SK_Kyln_Blue_EnergyHammer_AC",
	},
	{
		id =			180,
		name =			"SK_Kyln_Purple_EnergyHammer_AC",
		CustID =		"SK_Kyln_Purple_EnergyHammer_AC",
		lock =			"CUST_SK_Kyln_Purple_EnergyHammer_AC",
		icon =			"SK_Kyln_Purple_EnergyHammer_AC",
	},
	{
		id =			181,
		name =			"SK_Kyln_Green_SporeGun_AC",
		CustID =		"SK_Kyln_Green_SporeGun_AC",
		lock =			"CUST_SK_Kyln_Green_SporeGun_AC",
		icon =			"SK_Kyln_Green_SporeGun_AC",
	},
	{
		id =			182,
		name =			"SK_Kyln_Blue_SporeGun_AC",
		CustID =		"SK_Kyln_Blue_SporeGun_AC",
		lock =			"CUST_SK_Kyln_Blue_SporeGun_AC",
		icon =			"SK_Kyln_Blue_SporeGun_AC",
	},
	{
		id =			183,
		name =			"SK_Kyln_Purple_SporeGun_AC",
		CustID =		"SK_Kyln_Purple_SporeGun_AC",
		lock =			"CUST_SK_Kyln_Purple_SporeGun_AC",
		icon =			"SK_Kyln_Purple_SporeGun_AC",
	},
	{
		id =			184,
		name =			"SK_Kyln_Green_BlackholeGrenade_AC",
		CustID =		"SK_Kyln_Green_BlackholeGrenade_AC",
		lock =			"CUST_SK_Kyln_Green_BlackholeGrenade_AC",
		icon =			"SK_Kyln_Green_BlackholeGrenade_AC",
	},
	{
		id =			185,
		name =			"SK_Kyln_Blue_BlackholeGrenade_AC",
		CustID =		"SK_Kyln_Blue_BlackholeGrenade_AC",
		lock =			"CUST_SK_Kyln_Blue_BlackholeGrenade_AC",
		icon =			"SK_Kyln_Blue_BlackholeGrenade_AC",
	},
	{
		id =			186,
		name =			"SK_Kyln_Purple_BlackholeGrenade_AC",
		CustID =		"SK_Kyln_Purple_BlackholeGrenade_AC",
		lock =			"CUST_SK_Kyln_Purple_BlackholeGrenade_AC",
		icon =			"SK_Kyln_Purple_BlackholeGrenade_AC",
	},
	{
		id =			187,
		name =			"SK_Kyln_Green_HelmWhite1_HR",
		CustID =		"SK_Kyln_Green_HelmWhite1_HR",
		lock =			"CUST_SK_Kyln_Green_HelmWhite1_HR",
		icon =			"SK_Kyln_Green_HelmWhite1_HR",
	},
	{
		id =			188,
		name =			"SK_Kyln_Blue_HelmWhite1_HR",
		CustID =		"SK_Kyln_Blue_HelmWhite1_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmWhite1_HR",
		icon =			"SK_Kyln_Blue_HelmWhite1_HR",
	},
	{
		id =			189,
		name =			"SK_Kyln_Purple_HelmWhite1_HR",
		CustID =		"SK_Kyln_Purple_HelmWhite1_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmWhite1_HR",
		icon =			"SK_Kyln_Purple_HelmWhite1_HR",
	},
	{
		id =			190,
		name =			"SK_Kyln_Green_HelmWhite2_HR",
		CustID =		"SK_Kyln_Green_HelmWhite2_HR",
		lock =			"CUST_SK_Kyln_Green_HelmWhite2_HR",
		icon =			"SK_Kyln_Green_HelmWhite2_HR",
	},
	{
		id =			191,
		name =			"SK_Kyln_Blue_HelmWhite2_HR",
		CustID =		"SK_Kyln_Blue_HelmWhite2_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmWhite2_HR",
		icon =			"SK_Kyln_Blue_HelmWhite2_HR",
	},
	{
		id =			192,
		name =			"SK_Kyln_Purple_HelmWhite2_HR",
		CustID =		"SK_Kyln_Purple_HelmWhite2_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmWhite2_HR",
		icon =			"SK_Kyln_Purple_HelmWhite2_HR",
	},
	{
		id =			193,
		name =			"SK_Kyln_Green_HelmWhite3_HR",
		CustID =		"SK_Kyln_Green_HelmWhite3_HR",
		lock =			"CUST_SK_Kyln_Green_HelmWhite3_HR",
		icon =			"SK_Kyln_Green_HelmWhite3_HR",
	},
	{
		id =			194,
		name =			"SK_Kyln_Blue_HelmWhite3_HR",
		CustID =		"SK_Kyln_Blue_HelmWhite3_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmWhite3_HR",
		icon =			"SK_Kyln_Blue_HelmWhite3_HR",
	},
	{
		id =			195,
		name =			"SK_Kyln_Purple_HelmWhite3_HR",
		CustID =		"SK_Kyln_Purple_HelmWhite3_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmWhite3_HR",
		icon =			"SK_Kyln_Purple_HelmWhite3_HR",
	},
	{
		id =			196,
		name =			"SK_Kyln_Green_HelmWhite4_HR",
		CustID =		"SK_Kyln_Green_HelmWhite4_HR",
		lock =			"CUST_SK_Kyln_Green_HelmWhite4_HR",
		icon =			"SK_Kyln_Green_HelmWhite4_HR",
	},
	{
		id =			197,
		name =			"SK_Kyln_Blue_HelmWhite4_HR",
		CustID =		"SK_Kyln_Blue_HelmWhite4_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmWhite4_HR",
		icon =			"SK_Kyln_Blue_HelmWhite4_HR",
	},
	{
		id =			198,
		name =			"SK_Kyln_Purple_HelmWhite4_HR",
		CustID =		"SK_Kyln_Purple_HelmWhite4_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmWhite4_HR",
		icon =			"SK_Kyln_Purple_HelmWhite4_HR",
	},
	{
		id =			199,
		name =			"SK_Kyln_Green_HelmWhite5_HR",
		CustID =		"SK_Kyln_Green_HelmWhite5_HR",
		lock =			"CUST_SK_Kyln_Green_HelmWhite5_HR",
		icon =			"SK_Kyln_Green_HelmWhite5_HR",
	},
	{
		id =			200,
		name =			"SK_Kyln_Blue_HelmWhite5_HR",
		CustID =		"SK_Kyln_Blue_HelmWhite5_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmWhite5_HR",
		icon =			"SK_Kyln_Blue_HelmWhite5_HR",
	},
	{
		id =			201,
		name =			"SK_Kyln_Purple_HelmWhite5_HR",
		CustID =		"SK_Kyln_Purple_HelmWhite5_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmWhite5_HR",
		icon =			"SK_Kyln_Purple_HelmWhite5_HR",
	},
	{
		id =			202,
		name =			"SK_Kyln_Green_HelmGrey1_HR",
		CustID =		"SK_Kyln_Green_HelmGrey1_HR",
		lock =			"CUST_SK_Kyln_Green_HelmGrey1_HR",
		icon =			"SK_Kyln_Green_HelmGrey1_HR",
	},
	{
		id =			203,
		name =			"SK_Kyln_Blue_HelmGrey1_HR",
		CustID =		"SK_Kyln_Blue_HelmGrey1_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmGrey1_HR",
		icon =			"SK_Kyln_Blue_HelmGrey1_HR",
	},
	{
		id =			204,
		name =			"SK_Kyln_Purple_HelmGrey1_HR",
		CustID =		"SK_Kyln_Purple_HelmGrey1_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmGrey1_HR",
		icon =			"SK_Kyln_Purple_HelmGrey1_HR",
	},
	{
		id =			205,
		name =			"SK_Kyln_Green_HelmGrey2_HR",
		CustID =		"SK_Kyln_Green_HelmGrey2_HR",
		lock =			"CUST_SK_Kyln_Green_HelmGrey2_HR",
		icon =			"SK_Kyln_Green_HelmGrey2_HR",
	},
	{
		id =			206,
		name =			"SK_Kyln_Blue_HelmGrey2_HR",
		CustID =		"SK_Kyln_Blue_HelmGrey2_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmGrey2_HR",
		icon =			"SK_Kyln_Blue_HelmGrey2_HR",
	},
	{
		id =			207,
		name =			"SK_Kyln_Purple_HelmGrey2_HR",
		CustID =		"SK_Kyln_Purple_HelmGrey2_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmGrey2_HR",
		icon =			"SK_Kyln_Purple_HelmGrey2_HR",
	},
	{
		id =			208,
		name =			"SK_Kyln_Green_HelmGrey3_HR",
		CustID =		"SK_Kyln_Green_HelmGrey3_HR",
		lock =			"CUST_SK_Kyln_Green_HelmGrey3_HR",
		icon =			"SK_Kyln_Green_HelmGrey3_HR",
	},
	{
		id =			209,
		name =			"SK_Kyln_Blue_HelmGrey3_HR",
		CustID =		"SK_Kyln_Blue_HelmGrey3_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmGrey3_HR",
		icon =			"SK_Kyln_Blue_HelmGrey3_HR",
	},
	{
		id =			210,
		name =			"SK_Kyln_Purple_HelmGrey3_HR",
		CustID =		"SK_Kyln_Purple_HelmGrey3_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmGrey3_HR",
		icon =			"SK_Kyln_Purple_HelmGrey3_HR",
	},
	{
		id =			211,
		name =			"SK_Kyln_Green_HelmGrey4_HR",
		CustID =		"SK_Kyln_Green_HelmGrey4_HR",
		lock =			"CUST_SK_Kyln_Green_HelmGrey4_HR",
		icon =			"SK_Kyln_Green_HelmGrey4_HR",
	},
	{
		id =			212,
		name =			"SK_Kyln_Blue_HelmGrey4_HR",
		CustID =		"SK_Kyln_Blue_HelmGrey4_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmGrey4_HR",
		icon =			"SK_Kyln_Blue_HelmGrey4_HR",
	},
	{
		id =			213,
		name =			"SK_Kyln_Purple_HelmGrey4_HR",
		CustID =		"SK_Kyln_Purple_HelmGrey4_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmGrey4_HR",
		icon =			"SK_Kyln_Purple_HelmGrey4_HR",
	},
	{
		id =			214,
		name =			"SK_Kyln_Blue_HelmGrey5_HR",
		CustID =		"SK_Kyln_Blue_HelmGrey5_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmGrey5_HR",
		icon =			"SK_Kyln_Blue_HelmGrey5_HR",
	},
	{
		id =			215,
		name =			"SK_Kyln_Purple_HelmGrey5_HR",
		CustID =		"SK_Kyln_Purple_HelmGrey5_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmGrey5_HR",
		icon =			"SK_Kyln_Purple_HelmGrey5_HR",
	},
	{
		id =			216,
		name =			"SK_Kyln_Orange_HelmGrey5_HR",
		CustID =		"SK_Kyln_Orange_HelmGrey5_HR",
		lock =			"CUST_SK_Kyln_Orange_HelmGrey5_HR",
		icon =			"SK_Kyln_Orange_HelmGrey5_HR",
	},
	{
		id =			217,
		name =			"SK_Kyln_Blue_HelmRed1_HR",
		CustID =		"SK_Kyln_Blue_HelmRed1_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmRed1_HR",
		icon =			"SK_Kyln_Blue_HelmRed1_HR",
	},
	{
		id =			218,
		name =			"SK_Kyln_Purple_HelmRed1_HR",
		CustID =		"SK_Kyln_Purple_HelmRed1_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmRed1_HR",
		icon =			"SK_Kyln_Purple_HelmRed1_HR",
	},
	{
		id =			219,
		name =			"SK_Kyln_Orange_HelmRed1_HR",
		CustID =		"SK_Kyln_Orange_HelmRed1_HR",
		lock =			"CUST_SK_Kyln_Orange_HelmRed1_HR",
		icon =			"SK_Kyln_Orange_HelmRed1_HR",
	},
	{
		id =			220,
		name =			"SK_Kyln_Green_HelmRed2_HR",
		CustID =		"SK_Kyln_Green_HelmRed2_HR",
		lock =			"CUST_SK_Kyln_Green_HelmRed2_HR",
		icon =			"SK_Kyln_Green_HelmRed2_HR",
	},
	{
		id =			221,
		name =			"SK_Kyln_Blue_HelmRed2_HR",
		CustID =		"SK_Kyln_Blue_HelmRed2_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmRed2_HR",
		icon =			"SK_Kyln_Blue_HelmRed2_HR",
	},
	{
		id =			222,
		name =			"SK_Kyln_Purple_HelmRed2_HR",
		CustID =		"SK_Kyln_Purple_HelmRed2_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmRed2_HR",
		icon =			"SK_Kyln_Purple_HelmRed2_HR",
	},
	{
		id =			223,
		name =			"SK_Kyln_Green_HelmRed3_HR",
		CustID =		"SK_Kyln_Green_HelmRed3_HR",
		lock =			"CUST_SK_Kyln_Green_HelmRed3_HR",
		icon =			"SK_Kyln_Green_HelmRed3_HR",
	},
	{
		id =			224,
		name =			"SK_Kyln_Blue_HelmRed3_HR",
		CustID =		"SK_Kyln_Blue_HelmRed3_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmRed3_HR",
		icon =			"SK_Kyln_Blue_HelmRed3_HR",
	},
	{
		id =			225,
		name =			"SK_Kyln_Purple_HelmRed3_HR",
		CustID =		"SK_Kyln_Purple_HelmRed3_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmRed3_HR",
		icon =			"SK_Kyln_Purple_HelmRed3_HR",
	},
	{
		id =			226,
		name =			"SK_Kyln_Green_HelmRed4_HR",
		CustID =		"SK_Kyln_Green_HelmRed4_HR",
		lock =			"CUST_SK_Kyln_Green_HelmRed4_HR",
		icon =			"SK_Kyln_Green_HelmRed4_HR",
	},
	{
		id =			227,
		name =			"SK_Kyln_Blue_HelmRed4_HR",
		CustID =		"SK_Kyln_Blue_HelmRed4_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmRed4_HR",
		icon =			"SK_Kyln_Blue_HelmRed4_HR",
	},
	{
		id =			228,
		name =			"SK_Kyln_Purple_HelmRed4_HR",
		CustID =		"SK_Kyln_Purple_HelmRed4_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmRed4_HR",
		icon =			"SK_Kyln_Purple_HelmRed4_HR",
	},
	{
		id =			229,
		name =			"SK_Kyln_Blue_HelmRed5_HR",
		CustID =		"SK_Kyln_Blue_HelmRed5_HR",
		lock =			"CUST_SK_Kyln_Blue_HelmRed5_HR",
		icon =			"SK_Kyln_Blue_HelmRed5_HR",
	},
	{
		id =			230,
		name =			"SK_Kyln_Purple_HelmRed5_HR",
		CustID =		"SK_Kyln_Purple_HelmRed5_HR",
		lock =			"CUST_SK_Kyln_Purple_HelmRed5_HR",
		icon =			"SK_Kyln_Purple_HelmRed5_HR",
	},
	{
		id =			231,
		name =			"SK_Kyln_Orange_HelmRed5_HR",
		CustID =		"SK_Kyln_Orange_HelmRed5_HR",
		lock =			"CUST_SK_Kyln_Orange_HelmRed5_HR",
		icon =			"SK_Kyln_Orange_HelmRed5_HR",
	},
	{
		id =			232,
		name =			"SK_Kyln_Green_ArmorWhite1_B",
		CustID =		"SK_Kyln_Green_ArmorWhite1_B",
		lock =			"CUST_SK_Kyln_Green_ArmorWhite1_B",
		icon =			"SK_Kyln_Green_ArmorWhite1_B",
	},
	{
		id =			233,
		name =			"SK_Kyln_Blue_ArmorWhite1_B",
		CustID =		"SK_Kyln_Blue_ArmorWhite1_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorWhite1_B",
		icon =			"SK_Kyln_Blue_ArmorWhite1_B",
	},
	{
		id =			234,
		name =			"SK_Kyln_Purple_ArmorWhite1_B",
		CustID =		"SK_Kyln_Purple_ArmorWhite1_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorWhite1_B",
		icon =			"SK_Kyln_Purple_ArmorWhite1_B",
	},
	{
		id =			235,
		name =			"SK_Kyln_Green_ArmorWhite2_B",
		CustID =		"SK_Kyln_Green_ArmorWhite2_B",
		lock =			"CUST_SK_Kyln_Green_ArmorWhite2_B",
		icon =			"SK_Kyln_Green_ArmorWhite2_B",
	},
	{
		id =			236,
		name =			"SK_Kyln_Blue_ArmorWhite2_B",
		CustID =		"SK_Kyln_Blue_ArmorWhite2_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorWhite2_B",
		icon =			"SK_Kyln_Blue_ArmorWhite2_B",
	},
	{
		id =			237,
		name =			"SK_Kyln_Purple_ArmorWhite2_B",
		CustID =		"SK_Kyln_Purple_ArmorWhite2_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorWhite2_B",
		icon =			"SK_Kyln_Purple_ArmorWhite2_B",
	},
	{
		id =			238,
		name =			"SK_Kyln_Green_ArmorWhite3_B",
		CustID =		"SK_Kyln_Green_ArmorWhite3_B",
		lock =			"CUST_SK_Kyln_Green_ArmorWhite3_B",
		icon =			"SK_Kyln_Green_ArmorWhite3_B",
	},
	{
		id =			239,
		name =			"SK_Kyln_Blue_ArmorWhite3_B",
		CustID =		"SK_Kyln_Blue_ArmorWhite3_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorWhite3_B",
		icon =			"SK_Kyln_Blue_ArmorWhite3_B",
	},
	{
		id =			240,
		name =			"SK_Kyln_Purple_ArmorWhite3_B",
		CustID =		"SK_Kyln_Purple_ArmorWhite3_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorWhite3_B",
		icon =			"SK_Kyln_Purple_ArmorWhite3_B",
	},
	{
		id =			241,
		name =			"SK_Kyln_Green_ArmorWhite4_B",
		CustID =		"SK_Kyln_Green_ArmorWhite4_B",
		lock =			"CUST_SK_Kyln_Green_ArmorWhite4_B",
		icon =			"SK_Kyln_Green_ArmorWhite4_B",
	},
	{
		id =			242,
		name =			"SK_Kyln_Blue_ArmorWhite4_B",
		CustID =		"SK_Kyln_Blue_ArmorWhite4_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorWhite4_B",
		icon =			"SK_Kyln_Blue_ArmorWhite4_B",
	},
	{
		id =			243,
		name =			"SK_Kyln_Purple_ArmorWhite4_B",
		CustID =		"SK_Kyln_Purple_ArmorWhite4_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorWhite4_B",
		icon =			"SK_Kyln_Purple_ArmorWhite4_B",
	},
	{
		id =			244,
		name =			"SK_Kyln_Green_ArmorWhite5_B",
		CustID =		"SK_Kyln_Green_ArmorWhite5_B",
		lock =			"CUST_SK_Kyln_Green_ArmorWhite5_B",
		icon =			"SK_Kyln_Green_ArmorWhite5_B",
	},
	{
		id =			245,
		name =			"SK_Kyln_Blue_ArmorWhite5_B",
		CustID =		"SK_Kyln_Blue_ArmorWhite5_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorWhite5_B",
		icon =			"SK_Kyln_Blue_ArmorWhite5_B",
	},
	{
		id =			246,
		name =			"SK_Kyln_Purple_ArmorWhite5_B",
		CustID =		"SK_Kyln_Purple_ArmorWhite5_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorWhite5_B",
		icon =			"SK_Kyln_Purple_ArmorWhite5_B",
	},
	{
		id =			247,
		name =			"SK_Kyln_Green_ArmorGrey1_B",
		CustID =		"SK_Kyln_Green_ArmorGrey1_B",
		lock =			"CUST_SK_Kyln_Green_ArmorGrey1_B",
		icon =			"SK_Kyln_Green_ArmorGrey1_B",
	},
	{
		id =			248,
		name =			"SK_Kyln_Blue_ArmorGrey1_B",
		CustID =		"SK_Kyln_Blue_ArmorGrey1_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorGrey1_B",
		icon =			"SK_Kyln_Blue_ArmorGrey1_B",
	},
	{
		id =			249,
		name =			"SK_Kyln_Purple_ArmorGrey1_B",
		CustID =		"SK_Kyln_Purple_ArmorGrey1_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorGrey1_B",
		icon =			"SK_Kyln_Purple_ArmorGrey1_B",
	},
	{
		id =			250,
		name =			"SK_Kyln_Green_ArmorGrey2_B",
		CustID =		"SK_Kyln_Green_ArmorGrey2_B",
		lock =			"CUST_SK_Kyln_Green_ArmorGrey2_B",
		icon =			"SK_Kyln_Green_ArmorGrey2_B",
	},
	{
		id =			251,
		name =			"SK_Kyln_Blue_ArmorGrey2_B",
		CustID =		"SK_Kyln_Blue_ArmorGrey2_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorGrey2_B",
		icon =			"SK_Kyln_Blue_ArmorGrey2_B",
	},
	{
		id =			252,
		name =			"SK_Kyln_Purple_ArmorGrey2_B",
		CustID =		"SK_Kyln_Purple_ArmorGrey2_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorGrey2_B",
		icon =			"SK_Kyln_Purple_ArmorGrey2_B",
	},
	{
		id =			253,
		name =			"SK_Kyln_Green_ArmorGrey3_B",
		CustID =		"SK_Kyln_Green_ArmorGrey3_B",
		lock =			"CUST_SK_Kyln_Green_ArmorGrey3_B",
		icon =			"SK_Kyln_Green_ArmorGrey3_B",
	},
	{
		id =			254,
		name =			"SK_Kyln_Blue_ArmorGrey3_B",
		CustID =		"SK_Kyln_Blue_ArmorGrey3_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorGrey3_B",
		icon =			"SK_Kyln_Blue_ArmorGrey3_B",
	},
	{
		id =			255,
		name =			"SK_Kyln_Purple_ArmorGrey3_B",
		CustID =		"SK_Kyln_Purple_ArmorGrey3_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorGrey3_B",
		icon =			"SK_Kyln_Purple_ArmorGrey3_B",
	},
	{
		id =			256,
		name =			"SK_Kyln_Green_ArmorGrey4_B",
		CustID =		"SK_Kyln_Green_ArmorGrey4_B",
		lock =			"CUST_SK_Kyln_Green_ArmorGrey4_B",
		icon =			"SK_Kyln_Green_ArmorGrey4_B",
	},
	{
		id =			257,
		name =			"SK_Kyln_Blue_ArmorGrey4_B",
		CustID =		"SK_Kyln_Blue_ArmorGrey4_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorGrey4_B",
		icon =			"SK_Kyln_Blue_ArmorGrey4_B",
	},
	{
		id =			258,
		name =			"SK_Kyln_Purple_ArmorGrey4_B",
		CustID =		"SK_Kyln_Purple_ArmorGrey4_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorGrey4_B",
		icon =			"SK_Kyln_Purple_ArmorGrey4_B",
	},
	{
		id =			259,
		name =			"SK_Kyln_Blue_ArmorGrey5_B",
		CustID =		"SK_Kyln_Blue_ArmorGrey5_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorGrey5_B",
		icon =			"SK_Kyln_Blue_ArmorGrey5_B",
	},
	{
		id =			260,
		name =			"SK_Kyln_Purple_ArmorGrey5_B",
		CustID =		"SK_Kyln_Purple_ArmorGrey5_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorGrey5_B",
		icon =			"SK_Kyln_Purple_ArmorGrey5_B",
	},
	{
		id =			261,
		name =			"SK_Kyln_Orange_ArmorGrey5_B",
		CustID =		"SK_Kyln_Orange_ArmorGrey5_B",
		lock =			"CUST_SK_Kyln_Orange_ArmorGrey5_B",
		icon =			"SK_Kyln_Orange_ArmorGrey5_B",
	},
	{
		id =			262,
		name =			"SK_Kyln_Blue_ArmorRed1_B",
		CustID =		"SK_Kyln_Blue_ArmorRed1_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorRed1_B",
		icon =			"SK_Kyln_Blue_ArmorRed1_B",
	},
	{
		id =			263,
		name =			"SK_Kyln_Purple_ArmorRed1_B",
		CustID =		"SK_Kyln_Purple_ArmorRed1_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorRed1_B",
		icon =			"SK_Kyln_Purple_ArmorRed1_B",
	},
	{
		id =			264,
		name =			"SK_Kyln_Orange_ArmorRed1_B",
		CustID =		"SK_Kyln_Orange_ArmorRed1_B",
		lock =			"CUST_SK_Kyln_Orange_ArmorRed1_B",
		icon =			"SK_Kyln_Orange_ArmorRed1_B",
	},
	{
		id =			265,
		name =			"SK_Kyln_Green_ArmorRed2_B",
		CustID =		"SK_Kyln_Green_ArmorRed2_B",
		lock =			"CUST_SK_Kyln_Green_ArmorRed2_B",
		icon =			"SK_Kyln_Green_ArmorRed2_B",
	},
	{
		id =			266,
		name =			"SK_Kyln_Blue_ArmorRed2_B",
		CustID =		"SK_Kyln_Blue_ArmorRed2_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorRed2_B",
		icon =			"SK_Kyln_Blue_ArmorRed2_B",
	},
	{
		id =			267,
		name =			"SK_Kyln_Purple_ArmorRed2_B",
		CustID =		"SK_Kyln_Purple_ArmorRed2_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorRed2_B",
		icon =			"SK_Kyln_Purple_ArmorRed2_B",
	},
	{
		id =			268,
		name =			"SK_Kyln_Green_ArmorRed3_B",
		CustID =		"SK_Kyln_Green_ArmorRed3_B",
		lock =			"CUST_SK_Kyln_Green_ArmorRed3_B",
		icon =			"SK_Kyln_Green_ArmorRed3_B",
	},
	{
		id =			269,
		name =			"SK_Kyln_Blue_ArmorRed3_B",
		CustID =		"SK_Kyln_Blue_ArmorRed3_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorRed3_B",
		icon =			"SK_Kyln_Blue_ArmorRed3_B",
	},
	{
		id =			270,
		name =			"SK_Kyln_Purple_ArmorRed3_B",
		CustID =		"SK_Kyln_Purple_ArmorRed3_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorRed3_B",
		icon =			"SK_Kyln_Purple_ArmorRed3_B",
	},
	{
		id =			271,
		name =			"SK_Kyln_Green_ArmorRed4_B",
		CustID =		"SK_Kyln_Green_ArmorRed4_B",
		lock =			"CUST_SK_Kyln_Green_ArmorRed4_B",
		icon =			"SK_Kyln_Green_ArmorRed4_B",
	},
	{
		id =			272,
		name =			"SK_Kyln_Blue_ArmorRed4_B",
		CustID =		"SK_Kyln_Blue_ArmorRed4_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorRed4_B",
		icon =			"SK_Kyln_Blue_ArmorRed4_B",
	},
	{
		id =			273,
		name =			"SK_Kyln_Purple_ArmorRed4_B",
		CustID =		"SK_Kyln_Purple_ArmorRed4_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorRed4_B",
		icon =			"SK_Kyln_Purple_ArmorRed4_B",
	},
	{
		id =			274,
		name =			"SK_Kyln_Blue_ArmorRed5_B",
		CustID =		"SK_Kyln_Blue_ArmorRed5_B",
		lock =			"CUST_SK_Kyln_Blue_ArmorRed5_B",
		icon =			"SK_Kyln_Blue_ArmorRed5_B",
	},
	{
		id =			275,
		name =			"SK_Kyln_Purple_ArmorRed5_B",
		CustID =		"SK_Kyln_Purple_ArmorRed5_B",
		lock =			"CUST_SK_Kyln_Purple_ArmorRed5_B",
		icon =			"SK_Kyln_Purple_ArmorRed5_B",
	},
	{
		id =			276,
		name =			"SK_Kyln_Orange_ArmorRed5_B",
		CustID =		"SK_Kyln_Orange_ArmorRed5_B",
		lock =			"CUST_SK_Kyln_Orange_ArmorRed5_B",
		icon =			"SK_Kyln_Orange_ArmorRed5_B",
	},
 }
