--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--


--Version = 0.3

Data =
{
	DBName = "Locks",
	Type = "Locks",
	Version = 0.3,
	ID = 223,
	TableName = "locks",
	Records =
	{
		{
			UID = 87877,
			name = 'CC_AV_NOVA',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "3\x8c\xb5i\x81\x88)\xddx\xb8m\x02y\xe5~ ",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_Nova",
				},
			},
		},
		{
			UID = 87873,
			name = 'CC_AV_ROCRAC',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "E\xf3]\xa8M\x06\x03\x1e\xcf(\x034`\xb5\xa5\x13",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_RocketRacoon",
				},
			},
		},
		{
			UID = 84924,
			name = 'INV_AVG_MiniHelicarrier',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd8igV,\xf1\f(\x04\xa0\x1aC\b\xd0\x14\x1b",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_MiniHelicarrier",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 85405,
			name = 'INV_AVG_Stark_SportsCar',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xf9;\xf2\xcc\xaa\xffc\xea\x19\x8dCME\x8a|%",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Stark_SportsCar",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 88660,
			name = 'INV_NPC_RR_BlackWidow',
			iconname = 'RR_BlackWidow_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "f\x8d\x84=\x1a~N\xa6H\x98\x868:\xdf\x04)",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_BlackWidow",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_BlackWidow",
				},
			},
		},
		{
			UID = 88634,
			name = 'INV_NPC_RR_CaptainAmerica',
			iconname = 'RR_CaptainAmerica_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "WW\x92\x06o\x94\xa1\x1c[\b\x19\xcb\xf6u\xb7\xe6",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_CaptainAmerica",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_CaptainAmerica",
				},
			},
		},
		{
			UID = 88623,
			name = 'INV_NPC_RR_Falcon',
			iconname = 'RR_Falcon_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xf6Z\xf98d\xf0\xdc\x89\n\xa0[\xb7j\xc8\x8b\xfd",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Falcon",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Falcon",
				},
			},
		},
		{
			UID = 88666,
			name = 'INV_NPC_RR_Hawkeye',
			iconname = 'RR_Hawkeye_AC',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xc3\xd4.t\x12\x9fU\xdf\xec\x8c\xdf\x16E9?4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Hawkeye",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Hawkeye",
				},
			},
		},
		{
			UID = 88630,
			name = 'INV_NPC_RR_Hulk',
			iconname = 'RR_Hulk_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "Pt\xef\x8d\xdar\x8e\xcaH\x15ZVb\xdf\x0f\xf3",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Hulk",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Hulk",
				},
			},
		},
		{
			UID = 88549,
			name = 'INV_NPC_RR_IronMan',
			iconname = 'RR_IronMan_HR',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x90swN08 \xf9\x7fd\xc3\xe6\x8b\xea7}",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_IronMan",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_IronMan",
				},
			},
		},
		{
			UID = 88681,
			name = 'INV_NPC_RR_Loki',
			iconname = 'RR_Loki_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "5k\x06\vmE0x\xe5\x9c\x97>W\xa4\"\x95",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Loki",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Loki",
				},
			},
		},
		{
			UID = 88584,
			name = 'INV_NPC_RR_Thor',
			iconname = 'RR_Thor_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x1f\xd6\xcd\xfb/|m\xde\xf2\x94|,|\xb5\xa0i",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Thor",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Thor",
				},
			},
		},
		{
			UID = 84998,
			name = 'INV_SPD_SHLD_EmergencyVehicle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "~\x02^\xa9\xcc\xee\x10\xc05?8\xfc\xfd\xa6\x8d\xae",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_SHLD_EmergencyVehicle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
		{
			UID = 113156,
			name = 'INV_TB_SHLD_Motorcycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\xd1\xe6\xb4\xbd>\xdfm\x7fG\b\x14\x87\fN<\xc4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_SHLD_Motorcycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 113165,
			name = 'INV_TB_Skycycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "0\nX\xc4`\xf6^\x10\xf4\x91;\xab@>\xd3\x8b",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Skycycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 113162,
			name = 'INV_TB_Snowmobile',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\xe4\xf6\xa7\xd3\\\xb3\x92;\x99\x99\xcf\x11\xc3\x10\x8c!",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Snowmobile",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
	},
}
