--*************************************************
--
-- THIS IS A GENERATED FILE. DO NOT HAND EDIT IT.
-- Generated by Game/Content/Bitmasks/Scripts/TypeDataHelpers.lua
--
--*************************************************

Data =
{
	Version = 0.0,
	Package = 'BattleArena',
	Sets =
	{
		-- Engine Masks/Filters
		{
			set = 'ActorState',
			properties =
			{
				DefaultBitmaskSize = 15,
				Type = 'Properties',
				CreateBitsOnDemand = true,
			},
			count = 2,
			masks =
			{
				{	mask='MBA_FrameActor', 	UID=8279 },
				{	mask='MBA_NoKnockBack', 	UID=8579 },
			},
		},
		{
			set = 'ActorTag',
			properties =
			{
				DefaultBitmaskSize = 5,
				Type = 'Properties',
				CreateBitsOnDemand = true,
			},
			count = 6,
			masks =
			{
				{	mask='MG_Tutorial_01', 	UID=8484 },
				{	mask='MG_Tutorial_02', 	UID=8487 },
				{	mask='MG_Tutorial_03', 	UID=8488 },
				{	mask='MG_Tutorial_04', 	UID=8483 },
				{	mask='MG_Tutorial_05', 	UID=8486 },
				{	mask='MG_Tutorial_06', 	UID=8485 },
			},
		},
		{
			set = 'ActorType',
			properties =
			{
				DefaultBitmaskSize = 6,
				Type = 'Properties',
			},
			count = 71,
			masks =
			{
				{	mask='AV_BlackPanther', 	UID=8308 },
				{	mask='AV_BlackWidow', 	UID=4356 },
				{	mask='AV_CaptainAmerica', 	UID=4353 },
				{	mask='AV_CaptainAmerica_CW', 	UID=8321 },
				{	mask='AV_Drax', 	UID=4396 },
				{	mask='AV_Falcon', 	UID=5258 },
				{	mask='AV_Gamora', 	UID=4503 },
				{	mask='AV_GreenGoblin', 	UID=5059 },
				{	mask='AV_Groot', 	UID=4369 },
				{	mask='AV_Hawkeye', 	UID=4350 },
				{	mask='AV_Hulk', 	UID=4343 },
				{	mask='AV_HulkBuster', 	UID=6746 },
				{	mask='AV_HulkBuster_Premium', 	UID=8383 },
				{	mask='AV_Hulk_Premium', 	UID=8378 },
				{	mask='AV_IronFist', 	UID=4393 },
				{	mask='AV_IronMan', 	UID=4342 },
				{	mask='AV_Loki', 	UID=4352 },
				{	mask='AV_Loki_Decoy', 	UID=5441 },
				{	mask='AV_NickFury', 	UID=4341 },
				{	mask='AV_NickFury_Decoy', 	UID=5073 },
				{	mask='AV_Nova', 	UID=4392 },
				{	mask='AV_RocketRaccoon', 	UID=4370 },
				{	mask='AV_Ronan', 	UID=4389 },
				{	mask='AV_Spiderman', 	UID=4344 },
				{	mask='AV_StarLord', 	UID=4386 },
				{	mask='AV_Thor', 	UID=4355 },
				{	mask='AV_Ultron', 	UID=7737 },
				{	mask='AV_UltronBot', 	UID=7826 },
				{	mask='AV_Venom', 	UID=4377 },
				{	mask='AV_Vision', 	UID=8306 },
				{	mask='AV_Yondu', 	UID=5228 },
				{	mask='GOG_Yondu', 	UID=4887 },
				{	mask='GoG_Starlord_Turret', 	UID=5627 },
				{	mask='MG_Generic', 	UID=212 },
				{	mask='SPD_GoblinGlider', 	UID=4709 },
				{	mask='SPD_WebGrapple', 	UID=4853 },
			},
			filters = 
			{
				{	filter='AV_AvatarAvengers', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor', 	UID=4374 },
				{	filter='AV_AvatarDecoy', 	desc='AV_NickFury_Decoy|AV_Loki_Decoy', 	UID=5494 },
				{	filter='AV_AvatarGuardians', 	desc='AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu', 	UID=4368 },
				{	filter='AV_AvatarSpiderman', 	desc='AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=4373 },
				{	filter='AV_BruteClass', 	desc='AV_Venom|AV_GreenGoblin|AV_Hulk|AV_Hulk_Premium', 	UID=5270 },
				{	filter='AV_Fliers', 	desc='AV_Falcon|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Nova|AV_Thor|AV_Ultron', 	UID=5668 },
				{	filter='AV_HeroClass', 	desc='AV_Drax|AV_BlackPanther|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_IronMan|AV_Thor|AV_Falcon|AV_HulkBuster|AV_HulkBuster_Premium|AVG_HulkBusterMBA|AV_Ultron|AV_Vision|AV_BlackPanther|AV_CaptainAmerica_CW|AV_Ultron|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_CaptainAmerica|AV_Thor|AV_Vision', 	UID=5359 },
				{	filter='AV_HeroFemaleClass', 	desc='AV_Gamora|AV_BlackWidow', 	UID=5357 },
				{	filter='AV_HeroSmallClass', 	desc='AV_Spiderman|AV_Loki|AV_Groot|AV_StarLord|AV_IronFist|AV_NickFury|AV_Nova|AV_Hawkeye', 	UID=5360 },
				{	filter='AV_LightsaberBruteClass', 	desc='AV_HulkBuster|AV_HulkBuster_Premium|AV_Groot|AV_Ronan|AV_Venom|AV_GreenGoblin|AV_Hulk|AV_Hulk_Premium', 	UID=6041 },
				{	filter='AV_LightsaberGirlClass', 	desc='AV_BlackWidow', 	UID=7356 },
				{	filter='AV_LightsaberHeroClass', 	desc='AV_BlackPanther|AV_Ultron|AV_Vision|AV_Hawkeye|AV_Falcon|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_IronMan|AV_Thor|AV_Drax', 	UID=7026 },
				{	filter='AV_LightsaberHeroSmallClass', 	desc='AV_Spiderman|AV_Loki|AV_StarLord|AV_IronFist|AV_NickFury|AV_Nova|AV_Yondu', 	UID=6964 },
				{	filter='AV_LightsaberVanellopeClass', 	desc='AV_RocketRaccoon', 	UID=6963 },
				{	filter='AV_RaccoonClass', 	desc='AV_RocketRaccoon', 	UID=5690 },
				{	filter='AV_SuperJumpers', 	desc='AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Drax|AV_Gamora|AV_Hulk|AV_Hulk_Premium|AV_IronFist|AV_RocketRaccoon|AV_Spiderman|AV_StarLord|AV_Venom', 	UID=5667 },
				{	filter='AV_TankClass', 	desc='AV_HulkBuster|AV_HulkBuster_Premium|AV_Venom|AV_GreenGoblin|AV_Hulk|AV_Hulk_Premium|AV_Groot', 	UID=7720 },
				{	filter='AV_TechType', 	desc='AV_BlackWidow|AV_Hawkeye|AV_IronMan|AV_RocketRaccoon|AV_StarLord|AV_Yondu|AV_NickFury', 	UID=5872 },
				{	filter='AV_WallCrawlDamagers', 	desc='AV_Hulk|AV_Hulk_Premium|AV_Groot|AV_Venom', 	UID=5565 },
				{	filter='AV_WallCrawlers', 	desc='AV_Hulk|AV_Hulk_Premium|AV_Groot|AV_Drax|AV_Spiderman|AV_Venom|AV_BlackPanther', 	UID=5564 },
				{	filter='AV_WebSwingers', 	desc='AV_Spiderman|AV_Venom', 	UID=5669 },
				{	filter='GOG_FriendlyTurret', 	desc='GoG_Starlord_Turret', 	UID=5626 },
				{	filter='Gliders', 	desc='SPD_GoblinGlider', 	UID=4718 },
				{	filter='IGP_Marvel', 	desc='AV_BlackWidow|AV_CaptainAmerica|AV_Drax|AV_Falcon|AV_Gamora|AV_GreenGoblin|AV_Groot|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronFist|AV_IronMan|AV_Loki|AV_NickFury|AV_Nova|AV_RocketRaccoon|AV_Ronan|AV_Spiderman|AV_StarLord|AV_Thor|AV_Ultron|AV_Venom|AV_Yondu', 	UID=8158 },
				{	filter='MG_Any', 	desc='MG_Generic|GOG_Yondu', 	UID=206 },
				{	filter='RR_Friendlies', 	desc='MG_Generic|GOG_Yondu', 	UID=232 },
				{	filter='Vehicles', 	desc='SPD_GoblinGlider', 	UID=132 },
				{	filter='VehiclesCab', 	desc='SPD_GoblinGlider', 	UID=2082 },
			},
			metafilters = 
			{
				{	filter='AV_AvatarAny', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=24 },
				{	filter='AV_AvatarBiped', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=144 },
				{	filter='AV_IN2_AvatarAny', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=5235 },
				{	filter='AboutToBeAttackedList', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=2815 },
				{	filter='PlayerControllable', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom', 	UID=274 },
				{	filter='RR_zAny', 	desc='AV_BlackPanther|AV_BlackWidow|AV_CaptainAmerica|AV_CaptainAmerica_CW|AV_Falcon|AV_Hawkeye|AV_Hulk|AV_Hulk_Premium|AV_Ultron|AV_UltronBot|AV_Vision|AV_HulkBuster|AV_HulkBuster_Premium|AV_IronMan|AV_Loki|AV_Thor|AV_NickFury_Decoy|AV_Loki_Decoy|AV_Drax|AV_Gamora|AV_Groot|AV_RocketRaccoon|AV_Ronan|AV_StarLord|AV_Yondu|AV_GreenGoblin|AV_IronFist|AV_Nova|AV_NickFury|AV_Spiderman|AV_Venom|SPD_GoblinGlider', 	UID=2137 },
				{	filter='VehiclesFlying', 	desc='SPD_GoblinGlider', 	UID=3552 },
			},
		},
		{
			set = 'AvatarCreationKey',
			properties =
			{
			},
			count = 28,
			masks =
			{
				{	mask='ANT_AntManMBA', 	UID=8587 },
				{	mask='AVG_BlackPantherMBA', 	UID=8311 },
				{	mask='AVG_BlackWidowMBA', 	UID=8137 },
				{	mask='AVG_CaptainAmericaCWMBA', 	UID=8523 },
				{	mask='AVG_CaptainAmericaMBA', 	UID=8140 },
				{	mask='AVG_DraxMBA', 	UID=8337 },
				{	mask='AVG_FalconMBA', 	UID=8373 },
				{	mask='AVG_HawkeyeMBA', 	UID=8352 },
				{	mask='AVG_HulkBusterMBA', 	UID=8138 },
				{	mask='AVG_HulkMBA', 	UID=8351 },
				{	mask='AVG_IronManMBA', 	UID=8270 },
				{	mask='AVG_LokiMBA', 	UID=8399 },
				{	mask='AVG_RonanMBA', 	UID=8340 },
				{	mask='AVG_ThorMBA', 	UID=8290 },
				{	mask='AVG_UltronMBA', 	UID=8303 },
				{	mask='AVG_VisionMBA', 	UID=8310 },
				{	mask='GOG_GamoraMBA', 	UID=8139 },
				{	mask='GOG_GrootMBA', 	UID=8362 },
				{	mask='GOG_RocketRaccoonMBA', 	UID=8259 },
				{	mask='GOG_StarLordMBA', 	UID=8302 },
				{	mask='GOG_YonduMBA', 	UID=8409 },
				{	mask='SPD_GreenGoblinMBA', 	UID=8415 },
				{	mask='SPD_IronFistMBA', 	UID=8428 },
				{	mask='SPD_NickFuryMBA', 	UID=8257 },
				{	mask='SPD_NovaMBA', 	UID=8292 },
				{	mask='SPD_SpiderManMBA', 	UID=8285 },
				{	mask='SPD_Spiderman_Black', 	UID=8243 },
				{	mask='SPD_VenomMBA', 	UID=8127 },
			},
		},
	}
}
