--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--


--Version = 0.3

Data =
{
	DBName = "Locks",
	Type = "Locks",
	Version = 0.3,
	ID = 156,
	TableName = "locks",
	Records =
	{
		{
			UID = 87877,
			name = 'CC_AV_NOVA',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\x98\xbd#P\xef\xe6O\x1e1&\xdb>\x8db\xd0\xc9",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_Nova",
				},
			},
		},
		{
			UID = 87873,
			name = 'CC_AV_ROCRAC',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "Q\xbd\xd1\xbe\xdd#>~^6`\x8c\x95\xa2\x8d\xe9",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_RocketRacoon",
				},
			},
		},
		{
			UID = 84924,
			name = 'INV_AVG_MiniHelicarrier',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xcb\x00\x8b-m\xebeIRIIk{\xa78W",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_MiniHelicarrier",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 85405,
			name = 'INV_AVG_Stark_SportsCar',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xdb#\xcb\x1b\x85\xfcB5h!\xf2\x14R\x9f\"\x8f",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Stark_SportsCar",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 88660,
			name = 'INV_NPC_RR_BlackWidow',
			iconname = 'RR_BlackWidow_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xb8\xfd\xf5,ZI\xb9\xcb\t2\x10\xfa'\xe1\xf4q",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_BlackWidow",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_BlackWidow",
				},
			},
		},
		{
			UID = 88634,
			name = 'INV_NPC_RR_CaptainAmerica',
			iconname = 'RR_CaptainAmerica_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "R\x8f\xbb\xed\xcc\xa0>2\x1d\x10{\xe0\x9e\xa6\xa1\xbc",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_CaptainAmerica",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_CaptainAmerica",
				},
			},
		},
		{
			UID = 88623,
			name = 'INV_NPC_RR_Falcon',
			iconname = 'RR_Falcon_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xcd\x1bZ\xc3L\xf5=\x98@\xca\xda_\x15\xc5\xa6\x0f",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Falcon",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Falcon",
				},
			},
		},
		{
			UID = 88666,
			name = 'INV_NPC_RR_Hawkeye',
			iconname = 'RR_Hawkeye_AC',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xea\xaf\x1a\xfe\xeen\x01\xabx-4\xfc\xe4\x85\xb5\xfc",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Hawkeye",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Hawkeye",
				},
			},
		},
		{
			UID = 88630,
			name = 'INV_NPC_RR_Hulk',
			iconname = 'RR_Hulk_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xc8\xef%\xa7\x136\xf5\xadf>0\xaf\xa8\x85K4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Hulk",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Hulk",
				},
			},
		},
		{
			UID = 88549,
			name = 'INV_NPC_RR_IronMan',
			iconname = 'RR_IronMan_HR',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xe7\x8d\x1cK~]\xde\x8b\xfc\xd5\x90\xdc\xb0\x11\xdc\xd9",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_IronMan",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_IronMan",
				},
			},
		},
		{
			UID = 88681,
			name = 'INV_NPC_RR_Loki',
			iconname = 'RR_Loki_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xe7/F\xc3\x8d)L\x89X\xc0\xfa\xcb\xf5\xd4\xb1\x8d",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Loki",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Loki",
				},
			},
		},
		{
			UID = 88584,
			name = 'INV_NPC_RR_Thor',
			iconname = 'RR_Thor_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xbaK/a\xa2\xd9\xebJ\xbf\xd2f\xb3\tUe\xff",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Thor",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "AVG_Thor",
				},
			},
		},
		{
			UID = 84998,
			name = 'INV_SPD_SHLD_EmergencyVehicle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "N\xccJ4w\xc9\xe3\x1a0.\x9e0\x89\xd1\x99R",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_SHLD_EmergencyVehicle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
		{
			UID = 113156,
			name = 'INV_TB_SHLD_Motorcycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\xf5>V\xfc 8\x0f2y\x10\xffI\x01\x0e\xf1:",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_SHLD_Motorcycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 113165,
			name = 'INV_TB_Skycycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\x92\xd7\xfa\x06s\xaf\x8a\x04[\\c\x95\xa6${u",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Skycycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
		{
			UID = 113162,
			name = 'INV_TB_Snowmobile',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_AVENGERS',
			doNotSave = 0,
			stateData = "\x83\xe9j\xf3\xd6\x99M\a,\xd2x\x13\xa8%c%",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "AVG_Snowmobile",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "Avengers",
				},
			},
		},
	},
}
