--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--


--Version = 0.3

Data =
{
	DBName = "Locks",
	Type = "Locks",
	Version = 0.3,
	ID = 225,
	TableName = "locks",
	Records =
	{
		{
			UID = 116816,
			name = 'INV_MBA_EXP_Asgard_Crate',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "2\x19\tr\x10G\xc3\rXh]>\xa9@\xa4\xd7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Asgard_Crate",
				},
			},
		},
		{
			UID = 116804,
			name = 'INV_MBA_EXP_Cannister',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "+A\xd7G\t\xf9\x99\xb5\x0fWg5Cc\xac\xad",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Cannister",
				},
			},
		},
		{
			UID = 116826,
			name = 'INV_MBA_EXP_CrateWoodA',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xe4\x92S\xb9\x9d~\x9fypk/\xef\xb6P\x14\xe1",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_CrateWoodA",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116797,
			name = 'INV_MBA_EXP_CrateWoodB',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "<\bi\xae\x0e1\x96~\xdd\x1d\xf6!b\x11~w",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_CrateWoodB",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116824,
			name = 'INV_MBA_EXP_LunarBase_Barrel',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd8\x19S\xcc\xda\x1c\x8a\xfdN\x8a\x04\x93\xc8\xc8q6",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_Barrel",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116810,
			name = 'INV_MBA_EXP_LunarBase_CrateL',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "]\x1b\xa7j\x80\x98\xfd\xca\x1f\xa2\xef\xbb\x16\a\xfd\x13",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_CrateL",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116805,
			name = 'INV_MBA_EXP_LunarBase_CrateS',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\b)\xa9m\xaf\xa0\xc9\xee|\x81\x11\x15.w\bt",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_CrateS",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116814,
			name = 'INV_MBA_EXP_LunarBase_EXP_Barrel',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xa1S\xb8\xbf\x19\x94\xded\a\x1a\xe1\x1bj*\x7fz",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_EXP_Barrel",
				},
			},
		},
		{
			UID = 116820,
			name = 'INV_MBA_EXP_LunarBase_FRZ_Barrel',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd6\x94\xfb\xda\xc7\x1bY\xbe3\xf6\xd6\xfd++\xab\xaa",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_FRZ_Barrel",
				},
			},
		},
		{
			UID = 116818,
			name = 'INV_MBA_EXP_LunarBase_Freeze_CrateS',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x7f`\xc3\xc3q\x05\xf9@R\xfb\x96E6\xbd7\xbf",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_LunarBase_Freeze_CrateS",
				},
			},
		},
		{
			UID = 116821,
			name = 'INV_MBA_EXP_Sewers_PipeRack',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x96\xfe$\xd7\xc2VCM\xe3Pk\x9d\xc6\xd3\xc8;",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Sewers_PipeRack",
				},
			},
		},
		{
			UID = 116806,
			name = 'INV_MBA_EXP_Trainyard_Flatbed',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xe4\xa9\xae\xc9[g\xcf\x8f?\xe1\xc7\tcCd\xc6",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Trainyard_Flatbed",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116828,
			name = 'INV_MBA_EXP_Trainyard_SubwayCar',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "#\tMqx\xe6Z\xa2\x85@\x9c@\xa4\xff\\i",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Trainyard_SubwayCar",
				},
			},
		},
		{
			UID = 116831,
			name = 'INV_MBA_EXP_Trainyard_Tanker',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x19\"\x00\xcce\xb5\x119\xe4R\xa9/\xcf\x1c\xd8k",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_Trainyard_Tanker",
				},
			},
		},
		{
			UID = 116823,
			name = 'INV_MBA_EXP_U_UltronArmB',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\a\x02\xd5l\x96{\xec\x8b\xb3\x8d\x95\x1afs\x91\xe1",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_U_UltronArmB",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116798,
			name = 'INV_MBA_EXP_WK_BarrelVibranium',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x89~\xe2\xbb\x05\xf5P\x19\xd7\xaf\xf4\xb0\xe4\f[z",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_BarrelVibranium",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116796,
			name = 'INV_MBA_EXP_WK_Bulldozer',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x891gdYb\x81>\x80\x92;{N1q\x04",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_Bulldozer",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116808,
			name = 'INV_MBA_EXP_WK_CliffA',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "=\x14\x1414\v\x0ea\ns\xc0\xa1\x04\xd3I\x05",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CliffA",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116815,
			name = 'INV_MBA_EXP_WK_CliffB',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\"\xfa\xaf\xda\x1e\x99\xa0\x8c-\xa2H\xb9\xf74\x99\xfb",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CliffB",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116827,
			name = 'INV_MBA_EXP_WK_CliffC',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x16'{\xa3V_\xb9\x94\xcaF\xb4\xeb\x02.\"\xf5",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CliffC",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116799,
			name = 'INV_MBA_EXP_WK_CliffD',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\a\xf2~\xa5\x91q_\x00,i\xae\xee\xe1\xe1T\x96",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CliffD",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116803,
			name = 'INV_MBA_EXP_WK_CliffE',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xad7P\xb3\xdc\xbe4\xa5eOd\x8c\x1d\xa2\xa1\xe7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CliffE",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116825,
			name = 'INV_MBA_EXP_WK_CrateVibranium',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xb3\v\xce\x14\xd3\b\x13\x82<.=!\x93\xac7$",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_CrateVibranium",
				},
			},
		},
		{
			UID = 116830,
			name = 'INV_MBA_EXP_WK_RockB',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "w%\xe9\xf03\xfe\v\x9f\xf9\xa9\x97\xfc\x18\xca\x03~",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_EXP_WK_RockB",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116813,
			name = 'INV_MBA_KW_Barrel_C_red',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "!'?=K\x1f$\x87\xbbu\xdc\x04\xf3q\xa7\xc5",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_KW_Barrel_C_red",
				},
			},
		},
		{
			UID = 116833,
			name = 'INV_MBA_KW_Crate_A',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x03\x1f\x02X\xe8V6e\x8b\xfd\f\xa6\xb5u\x9b\xfe",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_KW_Crate_A",
				},
			},
		},
		{
			UID = 116809,
			name = 'INV_MBA_Trainyard_Container_Car',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xc4\x8d[6\xc3\x1f\xb10\xfc\xea\x0e+\x96\xff\\O",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_Trainyard_Container_Car",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116794,
			name = 'INV_MBA_Trainyard_Container_Car_B',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "VO\x9eD\n\x90\xaa\xa1\xbd\xa6\xf1\x1dZ$K\x89",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_Trainyard_Container_Car_B",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116829,
			name = 'INV_MBA_Trainyard_Container_Car_C',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "9Z\xf1\x8e@\xa9g`{D\n\x8c\xea)\x06\xc4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "MBA_Trainyard_Container_Car_C",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116817,
			name = 'INV_SETPIECE_MBA_U_UltronBoss',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "ae\xfbTm\x00\r\xcd\xa0W\x02%\x88?\xb6\xe6",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SETPIECE_MBA_U_UltronBoss",
				},
			},
		},
		{
			UID = 114182,
			name = 'INV_SetPiece_MBA_Knowhere_Portal',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "(\xa6\x90?\x12\xa8\xa0\xfb\xf6\x02\x04!\x87Z\xe3H",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SetPiece_MBA_Knowhere_Portal",
				},
			},
		},
		{
			UID = 116819,
			name = 'INV_TOY_MBA_Asgard_ArchL',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd65\xe2\xeb\xb0\x181\v`\xc5U\x1a\xf8\x00.\xe3",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_ArchL",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116801,
			name = 'INV_TOY_MBA_Asgard_ArchR',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "3\xc3Z\x82\xcb\xaaM\xca\x19\xc4\xcby\x1d2\xa9\xb0",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_ArchR",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116795,
			name = 'INV_TOY_MBA_Asgard_Gate',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = " l'?\xaa\x81#\xdd\x93\xbe\xfc4\xd9\x01F\xa7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Gate",
				},
			},
		},
		{
			UID = 116802,
			name = 'INV_TOY_MBA_Asgard_Ice',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xee\xd9~\xba\x02\xa5\xc8]\xe25L\xbf\x16\xc4/:",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Ice",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116811,
			name = 'INV_TOY_MBA_Asgard_Icy_Rock',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "*7\xa6/\xf1\xe7\x8f\xb1u/:F\v\xe9\x9cA",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Icy_Rock",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116807,
			name = 'INV_TOY_MBA_Asgard_Urn',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd2\x85\xe3\x96\xb9P=\x0e\xd4\aJo8-sJ",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Urn",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 117464,
			name = 'INV_TOY_MBA_Asgard_Wall',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x0e\xaf\xe6OM\x91n\xfb\x17\xdf\n\xc6i\xb16\xbc",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Wall",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 117463,
			name = 'INV_TOY_MBA_Asgard_Wall_QuarterCircle',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = ">\x1f\x9e\x8e\xe2\xe2\x7f\xbc\xc1\xa4\xe8j\x93\x04w\xb5",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Asgard_Wall_QuarterCircle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 114188,
			name = 'INV_TOY_MBA_BuffStation_A',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xafq\x02\x91?\xd5\xa1\x8dNx\xfd\x947+q^",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_BuffStation_A",
				},
			},
		},
		{
			UID = 114185,
			name = 'INV_TOY_MBA_EXP_LunarBase_Rocket_TB',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "b\x89\x1c\xe6\xae\xec\xe9F[\x9d\xc6lo\xf4p\xa0",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_EXP_LunarBase_Rocket_TB",
				},
			},
		},
		{
			UID = 116832,
			name = 'INV_TOY_MBA_ElectricFloor',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xfdAt^B\xd6\x10\xe2o\x1c\xc9W\xc6\xd2\xa7\xc7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_ElectricFloor",
				},
			},
		},
		{
			UID = 114187,
			name = 'INV_TOY_MBA_LunarBase_GantryClaw',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xde\xe8[\x11Y\xfa\xdb\xf0\xd6OH\xcbIK59",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_LunarBase_GantryClaw",
				},
			},
		},
		{
			UID = 116822,
			name = 'INV_TOY_MBA_Trainyard_NYC_Billboard',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xc8N\xcd:\x890\x98_\x153\xca\xfd!\xf8y\xe1",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Trainyard_NYC_Billboard",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 114180,
			name = 'INV_TOY_MBA_Trainyard_TrackStraight',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xf5I7\xa6Nn0\xf1\x8fJ\xb4\x04H\xe6$\xa1",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Trainyard_TrackStraight",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 114183,
			name = 'INV_TOY_MBA_Trainyard_TrainStopper',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "S\xc4%\xb7UO\xf8O\x9e\x16\xdc\xc2\xcbw:\r",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Trainyard_TrainStopper",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116812,
			name = 'INV_TOY_MBA_Tutorial_Monitor',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd2i\xf3E!\x1b\x12\xca\xb3_\x95dd\xac)\xd7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Tutorial_Monitor",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "BattleArena",
				},
			},
		},
		{
			UID = 116800,
			name = 'INV_TOY_MBA_WK_MineCar',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xd6\xed\xc6\xb5\xa6:\x86y0T\xc9\xfe\xcd\xeb+\xfb",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_WK_MineCar",
				},
			},
		},
		{
			UID = 114184,
			name = 'INV_TOY_MBA_Wakanda_Drone',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xf5[\xff|\xb6)t\xe8\x90\xbf\x7f\x01\xbe-\x00\x19",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "TOY_MBA_Wakanda_Drone",
				},
			},
		},
		{
			UID = 114181,
			name = 'INV_Toy_MBA_ButtonCasingA',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "3\x842\xbc\xf7nL\x91\x96\x1f\\'\xd1\xe2ZI",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "Toy_MBA_ButtonCasingA",
				},
			},
		},
	},
}
