--
-- GENERATED BY customization_csv2game.lua, DO NOT MODIFY
--


--Version = 0.3

Data =
{
	DBName = "Locks",
	Type = "Locks",
	Version = 0.3,
	ID = 224,
	TableName = "locks",
	Records =
	{
		{
			UID = 87872,
			name = 'CC_SM_HULK',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\xa9\x98a\xa3.\"\xd9\rkH\x14\xcbaM\x8eC",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_Hulk",
				},
			},
		},
		{
			UID = 87875,
			name = 'CC_SM_IRONMAN',
			type = 'CROSSOVER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\xe5\xa0\xc0\x82\xd8g\xbc\xf2\xf6:,H\xe7\xd5\x85\xa4",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'IconName',
					val = "HUD_PlayerIcons_IronMan",
				},
			},
		},
		{
			UID = 88674,
			name = 'INV_NPC_RR_GreenGoblin',
			iconname = 'RR_GreenGoblin_AC-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = " \xa2\xf0\xb3\xc1\b\x8f5\x9d\x8f\x8e~]\x84\xdav",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_GreenGoblin",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_GreenGoblin",
				},
			},
		},
		{
			UID = 88553,
			name = 'INV_NPC_RR_IronFist',
			iconname = 'RR_IronFist_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "I\n\xa5\x16\x9d \xdf\xc4\xcbe3\xb0\x06\xe1\x167",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_IronFist",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_IronFist",
				},
			},
		},
		{
			UID = 88622,
			name = 'INV_NPC_RR_NickFury',
			iconname = 'RR_NickFury_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\x01\x95%\xf4c\x8d\x03\xe4\xe2\xa3\x96\x8e\x85\x91\xba\xbc",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_NickFury",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_NickFury",
				},
			},
		},
		{
			UID = 88615,
			name = 'INV_NPC_RR_Nova',
			iconname = 'RR_Nova_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "(\xed\xd6\xa5\xa0\x84\xab&M\xc4\t5`:p\x1f",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Nova",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Nova",
				},
			},
		},
		{
			UID = 88624,
			name = 'INV_NPC_RR_SpiderMan',
			iconname = 'RR_SpiderManBlack_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xe8\xdf\xbc\xd4\xc7\x85\x12y\xd1\xe4\xe2L\x16\x11?\xc3",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_SpiderMan",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Spiderman",
				},
			},
		},
		{
			UID = 88669,
			name = 'INV_NPC_RR_Venom',
			iconname = 'RR_Venom_B-hidden',
			type = 'TOYMAKER',
			filter = '',
			doNotSave = 0,
			stateData = "\xa5\x82\xb3A\xfd\xab\xa1\xbb\xe5\x03Y\x1a\n\xc1\x87\xb7",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "GroupUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "NPC_RR_Venom",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SPD_Venom",
				},
			},
		},
		{
			UID = 85510,
			name = 'INV_TB_HawkeyeSkycycle',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\xeb\x1c\xb3\fP?\x9b \x06\x17nW\xb1\x19\xfcF",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_HawkeyeSkycycle",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
		{
			UID = 113163,
			name = 'INV_TB_SHLD_Hovercar',
			type = 'TOYMAKER',
			filter = 'PlaySetFilter:LVL_SPIDERMAN',
			doNotSave = 0,
			stateData = "\x1cC\x8f\xba\v\x1b$\xb0h\xfd\x1a\x11\x05\xa46\x1f",
			dlcGroup = -1,
			unlock_data_int = 0,
			Categories = { },
			templateValues =
			{
				{
					type = 2,
					cpID = 'UnlockPresentation',
					val = "ChestUnlock",
				},
				{
					type = 2,
					cpID = 'IconName',
					val = "SPD_SHLD_Hovercar",
				},
				{
					type = 2,
					cpID = 'IGPName',
					val = "SpiderMan",
				},
			},
		},
	},
}
